---
title: "Figure 5 Code"
output: html_document
date: "2024-01-05"
---


```{r global-options, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, warning=FALSE, message=FALSE)
```

```{r loading libraries, include=FALSE}
# This code chunk loads various libraries necessary to complete the data analysis and produce graphics
library(tidyverse)
library(stringr)
library(ez)
library(cowplot)
library(viridis)
library(viridisLite)
library("readxl")
library("ggcorrplot")
library(dplyr)
library(ltm)
library(plotrix)
library("viridis")
library("paletteer")
library(ggpubr)
library(rstatix)
library(lme4)
#install.packages("lmerTest")
library(lmerTest)
#install.packages('emmeans')
library('emmeans')
library(grid)
library(gridExtra)
```

```{r reading data, include=FALSE}
# This data chunk loads and tidies up the data

# This loads the data file as the variable "data"
ya_data <- read.csv('~/Desktop/Research/NPRL/Papers/NavAging_Paper/data_analysis/ya_averaged_results.csv')
# Tidying up the data
ya_data<- ya_data %>% mutate(Age = 'YA')
ya_data
names(ya_data)[1] <- 'index'
names(ya_data)[2] <- 'Participant'
names(ya_data)[3] <- 'Block_num'
names(ya_data)[4] <- 'Total_Time'
names(ya_data)[5] <- 'Orientation_Time'
names(ya_data)[6] <- 'Navigation_Time'
names(ya_data)[7] <- 'Distance'
names(ya_data)[8] <- 'Speed'
names(ya_data)[9] <- 'Mean_Dwell'
names(ya_data)[10] <- 'Teleportations'
names(ya_data)[11] <- 'Age'
ya_data <- ya_data[ -c(1) ]
ya_data$Block_num <- as.factor(ya_data$Block_num)
sapply(ya_data, class)
ya_data

#This loads the data file as the variable "data"
oa_data <- read.csv('~/Desktop/Research/NPRL/Papers/NavAging_Paper/data_analysis/oa_averaged_results.csv')
# Tidying up the data
oa_data<- oa_data %>% mutate(Age = 'OA')
oa_data
names(oa_data)[1] <- 'index'
names(oa_data)[2] <- 'Participant'
names(oa_data)[3] <- 'Block_num'
names(oa_data)[4] <- 'Total_Time'
names(oa_data)[5] <- 'Orientation_Time'
names(oa_data)[6] <- 'Navigation_Time'
names(oa_data)[7] <- 'Distance'
names(oa_data)[8] <- 'Speed'
names(oa_data)[9] <- 'Mean_Dwell'
names(oa_data)[10] <- 'Teleportations'
names(oa_data)[11] <- 'Age'
oa_data <- oa_data[ -c(1) ]
oa_data$Block_num <- as.factor(oa_data$Block_num)
sapply(oa_data, class)
oa_data

data <- rbind(ya_data, oa_data)
```

```{r reading more data, include=FALSE}
#This loads the data file as the variable "data"
ya_nav_data <- read.csv('~/Desktop/Research/NPRL/Papers/NavAging_Paper/data_analysis/ya_merged_results.csv')
# Tidying up the data
ya_nav_data<- ya_nav_data %>% mutate(Age = 'YA')
names(ya_nav_data)[1] <- 'index'
names(ya_nav_data)[2] <- 'Participant'
names(ya_nav_data)[3] <- 'Block_num'
names(ya_nav_data)[4] <- 'Target_Name'
names(ya_nav_data)[5] <- 'Total_Time'
names(ya_nav_data)[6] <- 'Orientation_Time'
names(ya_nav_data)[7] <- 'Navigation_Time'
names(ya_nav_data)[8] <- 'Distance'
names(ya_nav_data)[9] <- 'Speed'
names(ya_nav_data)[10] <- 'Mean_Dwell'
names(ya_nav_data)[11] <- 'Teleportations'
names(ya_nav_data)[12] <- 'Age'
ya_nav_data <- ya_nav_data[ -c(1) ]
ya_nav_data$Block_num <- as.factor(ya_nav_data$Block_num)
sapply(ya_nav_data, class)

desired_order <- c("Automobile shop", "Police station ", "Fire Station", "Bank", "Pawn Shop", "Pizzeria", "Quattroki Restaurant", "High School")
# Reorder the levels of Target_Name
ya_nav_data$Target_Name <- factor(ya_nav_data$Target_Name, levels = desired_order)
pseudonym_map <- c("Automobile shop" = 'T1', "Police station "= 'T2', "Fire Station"= 'T3', "Bank"= 'T4', "Pawn Shop"= 'T5', "Pizzeria"= 'T6', "Quattroki Restaurant"= 'T7', "High School"= 'T8')
 
# Apply the mapping to the data frame
ya_nav_data <- ya_nav_data%>%
mutate(Target_Name = recode(Target_Name, !!!pseudonym_map))

#This loads the data file as the variable "data"
oa_nav_data <- read.csv('~/Desktop/Research/NPRL/Papers/NavAging_Paper/data_analysis/oa_merged_results.csv')
# Tidying up the data
oa_nav_data<- oa_nav_data %>% mutate(Age = 'OA')
names(oa_nav_data)[1] <- 'index'
names(oa_nav_data)[2] <- 'Participant'
names(oa_nav_data)[3] <- 'Block_num'
names(oa_nav_data)[4] <- 'Target_Name'
names(oa_nav_data)[5] <- 'Total_Time'
names(oa_nav_data)[6] <- 'Orientation_Time'
names(oa_nav_data)[7] <- 'Navigation_Time'
names(oa_nav_data)[8] <- 'Distance'
names(oa_nav_data)[9] <- 'Speed'
names(oa_nav_data)[10] <- 'Mean_Dwell'
names(oa_nav_data)[11] <- 'Teleportations'
names(oa_nav_data)[12] <- 'Age'
oa_nav_data <- oa_nav_data[ -c(1) ]
oa_nav_data$Block_num <- as.factor(oa_nav_data$Block_num)
sapply(oa_nav_data, class)

desired_order <- c("Automobile shop", "Police station ", "Fire Station", "Bank", "Pawn Shop", "Pizzeria", "Quattroki Restaurant", "High School")
# Reorder the levels of Target_Name
oa_nav_data$Target_Name <- factor(oa_nav_data$Target_Name, levels = desired_order)
pseudonym_map <- c("Automobile shop" = 'T1', "Police station "= 'T2', "Fire Station"= 'T3', "Bank"= 'T4', "Pawn Shop"= 'T5', "Pizzeria"= 'T6', "Quattroki Restaurant"= 'T7', "High School"= 'T8')
 
# Apply the mapping to the data frame
oa_nav_data <- oa_nav_data %>%
mutate(Target_Name = recode(Target_Name, !!!pseudonym_map))
nav_data <- rbind(ya_nav_data, oa_nav_data)
```

```{r reading more data, include=FALSE}
#This loads the data file as the variable "data"
non_nav_data <- read.csv('~/Desktop/Research/NPRL/Papers/NavAging_Paper/data_analysis/non_nav_data.csv')
# Tidying up the data
names(non_nav_data)[1] <- 'Participant'
names(non_nav_data)[2] <- 'Age'
names(non_nav_data)[3] <- 'PSQI'
names(non_nav_data)[4] <- 'SSS_Pre'
names(non_nav_data)[5] <- 'SSS_Post'
names(non_nav_data)[6] <- 'SBSOD'
names(non_nav_data)[7] <- 'MiniCog'
names(non_nav_data)[8] <- 'TrailsA'
names(non_nav_data)[9] <- 'TrailsB'
names(non_nav_data)[10] <- 'SetShifting'
names(non_nav_data)[11] <- 'CorsiBlocks'
names(non_nav_data)[12] <- 'SSQ_Pre'
names(non_nav_data)[13] <- 'SSQ_Post'
names(non_nav_data)[14] <- 'NARA'
```


```{r organizing data, include=FALSE}
b1 <- subset(nav_data, Block_num == 1)
rownames(b1) <- NULL
b2 <- subset(nav_data, Block_num == 2)
rownames(b2) <- NULL 
b3 <- subset(nav_data, Block_num == 3)
rownames(b3) <- NULL 

pseudonym_map <- c("Automobile shop" = 'T1', "Police station "= 'T2', "Fire Station"= 'T3', "Bank"= 'T4', "Pawn Shop"= 'T5', "Pizzeria"= 'T6', "Quattroki Restaurant"= 'T7', "High School"= 'T8')
 
# Apply the mapping to the data frame
nav_data <- nav_data %>%
mutate(Target_Name = recode(Target_Name, !!!pseudonym_map))
```


```{r ya organizing data, include=FALSE}
ya_b1 <- subset(ya_nav_data, Block_num == 1)
rownames(ya_b1) <- NULL
ya_b2 <- subset(ya_nav_data, Block_num == 2)
rownames(ya_b2) <- NULL
ya_b3 <- subset(ya_nav_data, Block_num == 3)
rownames(ya_b3) <- NULL

ya_b1$Target_Name <- factor(ya_b1$Target_Name, levels = desired_order)
ya_b2$Target_Name <- factor(ya_b2$Target_Name, levels = desired_order)
ya_b3$Target_Name <- factor(ya_b3$Target_Name, levels = desired_order)

ya_b1_targets <- ya_b1 %>%
  group_by(Target_Name) %>%
  summarize(Total_Time_m = mean(Total_Time),
            Total_Time_se = std.error(Total_Time),
            Orientation_Time_m = mean(Orientation_Time),
            Orientation_Time_se = std.error(Orientation_Time),
            Navigation_Time_m = mean(Navigation_Time),
            Navigation_Time_se = std.error(Navigation_Time),
            Distance_m = mean(Distance),
            Distance_se = std.error(Distance),
            Speed_m = mean(Speed),
            Speed_se = std.error(Speed),
            Mean_Dwell_m = mean(Mean_Dwell),
            Mean_Dwell_se = std.error(Mean_Dwell),
            Teleportations_m = mean(Teleportations),
            Teleportations_se = std.error(Teleportations))
ya_b1_targets <- ya_b1_targets %>% mutate(Age = 'YA')
ya_b1_targets$Block_num <- as.factor(1)
### USE THE CODE CHUNK ABOVE TO FIX
ya_b2_targets <- ya_b2 %>%
  group_by(Target_Name) %>%
  summarize(Total_Time_m = mean(Total_Time),
            Total_Time_se = std.error(Total_Time),
            Orientation_Time_m = mean(Orientation_Time),
            Orientation_Time_se = std.error(Orientation_Time),
            Navigation_Time_m = mean(Navigation_Time),
            Navigation_Time_se = std.error(Navigation_Time),
            Distance_m = mean(Distance),
            Distance_se = std.error(Distance),
            Speed_m = mean(Speed),
            Speed_se = std.error(Speed),
            Mean_Dwell_m = mean(Mean_Dwell),
            Mean_Dwell_se = std.error(Mean_Dwell),
            Teleportations_m = mean(Teleportations),
            Teleportations_se = std.error(Teleportations))
ya_b2_targets <- ya_b2_targets %>% mutate(Age = 'YA')
ya_b2_targets$Block_num <- as.factor(2)

ya_b3_targets <- ya_b3 %>%
  group_by(Target_Name) %>%
  summarize(Total_Time_m = mean(Total_Time),
            Total_Time_se = std.error(Total_Time),
            Orientation_Time_m = mean(Orientation_Time),
            Orientation_Time_se = std.error(Orientation_Time),
            Navigation_Time_m = mean(Navigation_Time),
            Navigation_Time_se = std.error(Navigation_Time),
            Distance_m = mean(Distance),
            Distance_se = std.error(Distance),
            Speed_m = mean(Speed),
            Speed_se = std.error(Speed),
            Mean_Dwell_m = mean(Mean_Dwell),
            Mean_Dwell_se = std.error(Mean_Dwell),
            Teleportations_m = mean(Teleportations),
            Teleportations_se = std.error(Teleportations))
ya_b3_targets <- ya_b3_targets %>% mutate(Age = 'YA')
ya_b3_targets$Block_num <- as.factor(3)

ya_test_allblocks_targets <- rbind(ya_b1_targets, ya_b2_targets, ya_b3_targets)
#ya_allblocks_targets <- distinct(ya_test_allblocks_targets)
```

```{r oa organizing data, include=FALSE}
oa_b1 <- subset(oa_nav_data, Block_num == 1)
rownames(oa_b1) <- NULL
oa_b2 <- subset(oa_nav_data, Block_num == 2)
rownames(oa_b2) <- NULL
oa_b3 <- subset(oa_nav_data, Block_num == 3)
rownames(oa_b3) <- NULL


oa_b1$Target_Name <- factor(oa_b1$Target_Name, levels = desired_order)
oa_b2$Target_Name <- factor(oa_b2$Target_Name, levels = desired_order)
oa_b3$Target_Name <- factor(oa_b3$Target_Name, levels = desired_order)
oa_b1_targets <- oa_b1 %>%
  group_by(Target_Name) %>%
  summarize(Total_Time_m = mean(Total_Time),
            Total_Time_se = std.error(Total_Time),
            Orientation_Time_m = mean(Orientation_Time),
            Orientation_Time_se = std.error(Orientation_Time),
            Navigation_Time_m = mean(Navigation_Time),
            Navigation_Time_se = std.error(Navigation_Time),
            Distance_m = mean(Distance),
            Distance_se = std.error(Distance),
            Speed_m = mean(Speed),
            Speed_se = std.error(Speed),
            Mean_Dwell_m = mean(Mean_Dwell),
            Mean_Dwell_se = std.error(Mean_Dwell),
            Teleportations_m = mean(Teleportations),
            Teleportations_se = std.error(Teleportations))
oa_b1_targets <- oa_b1_targets %>% mutate(Age = 'OA')
oa_b1_targets$Block_num <- as.factor(1)

oa_b2_targets <- oa_b2 %>%
  group_by(Target_Name) %>%
  summarize(Total_Time_m = mean(Total_Time),
            Total_Time_se = std.error(Total_Time),
            Orientation_Time_m = mean(Orientation_Time),
            Orientation_Time_se = std.error(Orientation_Time),
            Navigation_Time_m = mean(Navigation_Time),
            Navigation_Time_se = std.error(Navigation_Time),
            Distance_m = mean(Distance),
            Distance_se = std.error(Distance),
            Speed_m = mean(Speed),
            Speed_se = std.error(Speed),
            Mean_Dwell_m = mean(Mean_Dwell),
            Mean_Dwell_se = std.error(Mean_Dwell),
            Teleportations_m = mean(Teleportations),
            Teleportations_se = std.error(Teleportations))
oa_b2_targets <- oa_b2_targets %>% mutate(Age = 'OA')
oa_b2_targets$Block_num <- as.factor(2)

oa_b3_targets <- oa_b3 %>%
  group_by(Target_Name) %>%
  summarize(Total_Time_m = mean(Total_Time),
            Total_Time_se = std.error(Total_Time),
            Orientation_Time_m = mean(Orientation_Time),
            Orientation_Time_se = std.error(Orientation_Time),
            Navigation_Time_m = mean(Navigation_Time),
            Navigation_Time_se = std.error(Navigation_Time),
            Distance_m = mean(Distance),
            Distance_se = std.error(Distance),
            Speed_m = mean(Speed),
            Speed_se = std.error(Speed),
            Mean_Dwell_m = mean(Mean_Dwell),
            Mean_Dwell_se = std.error(Mean_Dwell),
            Teleportations_m = mean(Teleportations),
            Teleportations_se = std.error(Teleportations))
oa_b3_targets <- oa_b3_targets %>% mutate(Age = 'OA')
oa_b3_targets$Block_num <- as.factor(3)


oa_test_allblocks_targets <- rbind(oa_b1_targets, oa_b2_targets, oa_b3_targets)
#oa_allblocks_targets <- distinct(oa_test_allblocks_targets)
allblocks_targets <- rbind(ya_test_allblocks_targets, oa_test_allblocks_targets)

pseudonym_map <- c("Automobile shop" = 'T1', "Police station "= 'T2', "Fire Station"= 'T3', "Bank"= 'T4', "Pawn Shop"= 'T5', "Pizzeria"= 'T6', "Quattroki Restaurant"= 'T7', "High School"= 'T8')

# Apply the mapping to the data frame
allblocks_targets <- allblocks_targets %>%
  mutate(Target_Name = recode(Target_Name, !!!pseudonym_map))
```

```{r ct, fig.height = 5, fig.width = 30, fig.align = "center"}
#Data.summary for Total_Time for all blocks
# Total Time
oa_data_summary <- oa_nav_data %>%
  group_by(Target_Name, Block_num) %>%
  summarise(
    se = std.error(Total_Time),
    Total_Time = mean(Total_Time)
  )

ya_data_summary <- ya_nav_data %>%
  group_by(Target_Name, Block_num) %>%
  summarise(
    se = std.error(Total_Time),
    Total_Time = mean(Total_Time)
  )
library(ggplot2)
library(dplyr)

# Assuming `nav_data` contains all participants, grouped by Target_Name, Age, and Block_num
# We will use `oa_data_summary` and `ya_data_summary` for OA and YA summaries

p_ct <- ggplot(nav_data, aes(x = Block_num, y = Total_Time, color = Age)) + 
  scale_color_manual(values = c('YA' = '#FF9FAF', 'OA' = '#5E7AFA')) +
  
  # Facet by Target_Name (8 separate graphs)
  facet_wrap(~ Target_Name, scales = "free_y", ncol = 8) + 
  
  # Individual participant lines (YA and OA)
  geom_line(aes(group = Participant), alpha = 0.2) +
  
  # Individual participant points
  geom_point(size = 2, alpha = 0.2) +
  
  # Summary line for YA
  geom_line(data = ya_data_summary, aes(x = Block_num, y = Total_Time, group = 1), 
            color = '#FF9FAF', size = 1.5) +
  
  # Error band (standard deviation) for YA
  geom_ribbon(data = ya_data_summary, aes(x = Block_num, ymin = Total_Time - sd(Total_Time), 
                                          ymax = Total_Time + sd(Total_Time)), 
              alpha = 0.1, color = '#FF9FAF') +
  
  # Summary line for OA
  geom_line(data = oa_data_summary, aes(x = Block_num, y = Total_Time, group = 1), 
            color = '#5E7AFA', size = 1.5) +
  stat_summary(data = oa_data_summary, fun.data = mean_se, geom="errorbar",  width=0.2, size=1,  color='#5E7AFA', alpha = 1) +
  
  # Error band (standard deviation) for OA
  #geom_ribbon(data = oa_data_summary, aes(x = Block_num, ymin = Total_Time - sd(Total_Time), ymax = Total_Time + sd(Total_Time)), alpha = 0.1, color = '#5E7AFA') +
  
  # Plot theme
  theme_classic() +
  labs(color = "Age", y = "Total Time (s)", x = "Block Number") +
  ylim(0, 250) +
  theme(
    axis.line = element_line(linewidth = 0.5, colour = "#242526"),
    axis.ticks = element_line(linewidth = 0.2, colour = "#242526"),
    plot.title = element_text(hjust = 0.5),
    legend.position = "none",
    axis.text.x = element_text(size = 20),
    axis.text.y = element_text(size = 20),
    axis.title.y = element_text(size = 20),
    axis.title.x = element_text(size = 20),
    strip.text = element_text(size = 20)
  )

p_ct

ggsave(file="~/Desktop/Research/NPRL/Papers/NavAging_Paper/figure_creation/plots/fig5_ct.svg", height = 5, width = 30, plot=p_ct)
```
# Orientation Time

```{r orict, fig.height = 5, fig.width = 10, fig.align = "center"}
p_orict <- ggplot(allblocks_targets, aes(x=Block_num, y=Orientation_Time_m, color=Age)) + 
  scale_color_manual(values=c('YA' = '#FF9FAF', 'OA' = '#5E7AFA')) +
  geom_point(size = 3) + 
  geom_line(mapping = aes(group = Age, color = Age)) + 
  geom_errorbar(allblocks_targets, mapping = aes(x=Block_num, ymin=Orientation_Time_m-Orientation_Time_se, 
                    ymax=Orientation_Time_m+Orientation_Time_se, group = Age, color = Age), 
                width=0.2, size=1)+
  facet_grid(. ~ Target_Name) + 
  stat_smooth(method = "lm") +
  theme_classic() +
  labs(color= "Age", y="Orientation Time (s)", x = "Block Number") +
  ylim(0, 50) +
  theme(
    axis.line = element_line(linewidth = .5, colour = "#242526"),
    axis.ticks = element_line(linewidth = .2, colour = "#242526"),
    plot.title = element_text(hjust = 0.5),
    legend.position = "none",
    axis.text.x = element_text(size = 20),
    axis.text.y = element_text(size = 20),
    axis.title.y = element_text(size = 20),
    axis.title.x = element_text(size = 20),
    strip.text = element_text(size = 20)
  ) +
  panel_border()
p_orict

ggsave(file="~/Desktop/Research/NPRL/Papers/NavAging_Paper/figure_creation/plots/fig5_orict.svg", height = 5, width = 10, plot=p_orict)
```

# Navigation Time

```{r navct, fig.height = 5, fig.width = 10, fig.align = "center"}

p_navct <- ggplot(allblocks_targets, aes(x=Block_num, y=Navigation_Time_m, color=Age)) + 
  scale_color_manual(values=c('YA' = '#FF9FAF', 'OA' = '#5E7AFA')) +
  geom_point(size = 3) + 
  geom_line(mapping = aes(group = Age, color = Age)) + 
  geom_errorbar(allblocks_targets, mapping = aes(x=Block_num, ymin=Navigation_Time_m-Navigation_Time_se, 
                    ymax=Navigation_Time_m+Navigation_Time_se, group = Age, color = Age), 
                width=0.2, size=1)+
  facet_grid(. ~ Target_Name) + 
  stat_smooth(method = "lm") +
  theme_classic() +
  labs(color= "Age", y="Navigation Time (s)", x = "Block Number") +
  ylim(0, 250) +
  theme(
    axis.line = element_line(linewidth = .5, colour = "#242526"),
    axis.ticks = element_line(linewidth = .2, colour = "#242526"),
    plot.title = element_text(hjust = 0.5),
    legend.position = "none",
    axis.text.x = element_text(size = 20),
    axis.text.y = element_text(size = 20),
    axis.title.y = element_text(size = 20),
    axis.title.x = element_text(size = 20),
    strip.text = element_text(size = 20)
  ) +
  panel_border()
p_navct
ggsave(file="~/Desktop/Research/NPRL/Papers/NavAging_Paper/figure_creation/plots/fig5_navct.svg", height = 5, width = 10, plot=p_navct)
```

# Distance

```{r dt, fig.height = 5, fig.width = 10, fig.align = "center"}
p_dt <- ggplot(allblocks_targets, aes(x=Block_num, y=Distance_m, color=Age)) + 
  scale_color_manual(values=c('YA' = '#FF9FAF', 'OA' = '#5E7AFA')) +
  geom_point(size =3) + 
  geom_line(mapping = aes(group = Age, color = Age)) + 
  geom_errorbar(allblocks_targets, mapping = aes(x=Block_num, ymin=Distance_m-Distance_se, 
                    ymax=Distance_m+Distance_se, group = Age, color = Age), 
                width=0.2, size=1)+
  facet_grid(. ~ Target_Name) + 
  stat_smooth(method = "lm") +
  theme_classic() +
  labs(color= "Age", y="Distance (VR Units)", x = "Block Number") +
  ylim(0,1200)+
  theme(
    axis.line = element_line(linewidth = .5, colour = "#242526"),
    axis.ticks = element_line(linewidth = .2, colour = "#242526"),
    plot.title = element_text(hjust = 0.5),
    legend.position = "none",
    axis.text.x = element_text(size = 20),
    axis.text.y = element_text(size = 20),
    axis.title.y = element_text(size = 20),
    axis.title.x = element_text(size = 20),
    strip.text = element_text(size = 20)
  ) +
  panel_border()
p_dt

ggsave(file="~/Desktop/Research/NPRL/Papers/NavAging_Paper/figure_creation/plots/fig5_dt.svg", height = 5, width = 10, plot=p_dt)
```

# Speed

```{r speed, fig.height = 5, fig.width = 10, fig.align = "center"}

p_speed <- ggplot(allblocks_targets, aes(x=Block_num, y=Speed_m, color=Age)) + 
  scale_color_manual(values=c('YA' = '#FF9FAF', 'OA' = '#5E7AFA')) +
  geom_point(size =3) + 
  geom_line(mapping = aes(group = Age, color = Age)) + 
  geom_errorbar(allblocks_targets, mapping = aes(x=Block_num, ymin=Speed_m-Speed_se, 
                    ymax=Speed_m+Speed_se, group = Age, color = Age), 
                width=0.2, size=1)+
  facet_grid(. ~ Target_Name) + 
  stat_smooth(method = "lm") +
  theme_classic() +
  labs(color= "Age", y="Speed (VR Units / s)", x = "Block Number") +
  ylim(0,30)+
  theme(
    axis.line = element_line(linewidth = .5, colour = "#242526"),
    axis.ticks = element_line(linewidth = .2, colour = "#242526"),
    plot.title = element_text(hjust = 0.5),
    legend.position = "none",
    axis.text.x = element_text(size = 20),
    axis.text.y = element_text(size = 20),
    axis.title.y = element_text(size = 20),
    axis.title.x = element_text(size = 20),
    strip.text = element_text(size = 20)
  ) +
  panel_border()
p_speed

ggsave(file="~/Desktop/Research/NPRL/Papers/NavAging_Paper/figure_creation/plots/fig5_speed.svg", height = 5, width = 10, plot=p_speed)
```

# Dwell Time

```{r dwell, fig.height = 5, fig.width = 10, fig.align = "center"}

p_dwell <- ggplot(allblocks_targets, aes(x=Block_num, y=Mean_Dwell_m, color=Age)) + 
  scale_color_manual(values=c('YA' = '#FF9FAF', 'OA' = '#5E7AFA')) +
  geom_point(size = 3) + 
  geom_line(mapping = aes(group = Age, color = Age)) + 
  geom_errorbar(allblocks_targets, mapping = aes(x=Block_num, ymin=Mean_Dwell_m-Mean_Dwell_se, 
                    ymax=Mean_Dwell_m+Mean_Dwell_se, group = Age, color = Age), 
                width=0.2, size=1)+
  facet_grid(. ~ Target_Name) + 
  stat_smooth(method = "lm") +
  theme_classic() +
  labs(color= "Age", y="Dwell Time (s)", x = "Block Number") +
  ylim(0,5)+
  theme(
    axis.line = element_line(linewidth = .5, colour = "#242526"),
    axis.ticks = element_line(linewidth = .2, colour = "#242526"),
    plot.title = element_text(hjust = 0.5),
    legend.position = "none",
    axis.text.x = element_text(size = 20),
    axis.text.y = element_text(size = 20),
    axis.title.y = element_text(size = 20),
    axis.title.x = element_text(size = 20),
    strip.text = element_text(size = 20)
  ) +
  panel_border()
p_dwell
ggsave(file="~/Desktop/Research/NPRL/Papers/NavAging_Paper/figure_creation/plots/fig5_dwell.svg", height = 5, width = 10, plot=p_dwell)
```

# Teleportations

```{r teleport, fig.height = 5, fig.width = 10, fig.align = "center"}
p_teleport <- ggplot(allblocks_targets, aes(x=Block_num, y=Teleportations_m, color=Age)) + 
  scale_color_manual(values=c('YA' = '#FF9FAF', 'OA' = '#5E7AFA')) +
  geom_point(size = 3) + 
  geom_line(mapping = aes(group = Age, color = Age)) + 
  geom_errorbar(allblocks_targets, mapping = aes(x=Block_num, ymin=Teleportations_m-Teleportations_se, 
                    ymax=Teleportations_m+Teleportations_se, group = Age, color = Age), 
                width=0.2, size=1)+
  facet_grid(. ~ Target_Name) + 
  stat_smooth(method = "lm") +
  theme_classic() +
  labs(color= "Age", y="Teleportations (count)", x = "Block Number") +
  ylim(0,200)+
  theme(
    axis.line = element_line(linewidth = .5, colour = "#242526"),
    axis.ticks = element_line(linewidth = .2, colour = "#242526"),
    plot.title = element_text(hjust = 0.5),
    legend.position = "none",
    axis.text.x = element_text(size = 20),
    axis.text.y = element_text(size = 20),
    axis.title.y = element_text(size = 20),
    axis.title.x = element_text(size = 20),
    strip.text = element_text(size = 20)
  ) +
  panel_border()
p_teleport
ggsave(file="~/Desktop/Research/NPRL/Papers/NavAging_Paper/figure_creation/plots/fig5_teleport.svg", height =5, width = 10, plot=p_teleport)
```

```{r comp, fig.height = 25, fig.width = 15, fig.align = "center"}
p<-grid.arrange(p_speed, p_ct, p_orict, p_navct, p_dt, p_dwell, p_teleport, ncol=1, nrow=7)
p
ggsave(file="~/Desktop/Research/NPRL/Papers/NavAging_Paper/figure_creation/plots/composite_fig5.svg", height = 25, width =15, plot=p)

```
