---
title: "Figure 2 Code"
output: html_document
date: "2023-11-01"

#goal: Make vertical rain cloud plot oa and ya by mean of all 3 blocks
---


```{r global-options, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, warning=FALSE, message=FALSE)
```

```{r loading libraries, include=FALSE}
# This code chunk loads various libraries necessary to complete the data analysis and produce graphics
library(tidyverse)
library(stringr)
library(ez)
library(cowplot)
library("readxl")
library("ggcorrplot")
library(dplyr)
library(ltm)
library(plotrix)
library("viridis")
library("paletteer")
library(ggpubr)
library(rstatix)
library(lme4)
#install.packages("lmerTest")
library(lmerTest)
#install.packages('emmeans')
library('emmeans')
#install.packages("svglite")
library(svglite)
library(tidyquant)
library(ggdist)
library(ggthemes)
library(gghalves)
library(grid)
library(gridExtra)
```

```{r reading data, include=FALSE}
#This data chunk loads and tidies up the data

#This loads the data file as the variable "data"
ya_data <- read.csv('~/Desktop/Research/NPRL/Papers/NavAging_Paper/data_analysis/ya_averaged_results.csv')
# Tidying up the data
ya_data<- ya_data %>% mutate(Age = 'YA')
ya_data
names(ya_data)[1] <- 'index'
names(ya_data)[2] <- 'Participant'
names(ya_data)[3] <- 'Block_num'
names(ya_data)[4] <- 'Total_Time'
names(ya_data)[5] <- 'Orientation_Time'
names(ya_data)[6] <- 'Navigation_Time'
names(ya_data)[7] <- 'Distance'
names(ya_data)[8] <- 'Speed'
names(ya_data)[9] <- 'Mean_Dwell'
names(ya_data)[10] <- 'Teleportations'
names(ya_data)[11] <- 'Age'
ya_data <- ya_data[ -c(1) ]
ya_data$Block_num <- as.factor(ya_data$Block_num)
sapply(ya_data, class)
ya_data

#This loads the data file as the variable "data"
oa_data <- read.csv('~/Desktop/Research/NPRL/Papers/NavAging_Paper/data_analysis/oa_averaged_results.csv')
# Tidying up the data
oa_data<- oa_data %>% mutate(Age = 'OA')
oa_data
names(oa_data)[1] <- 'index'
names(oa_data)[2] <- 'Participant'
names(oa_data)[3] <- 'Block_num'
names(oa_data)[4] <- 'Total_Time'
names(oa_data)[5] <- 'Orientation_Time'
names(oa_data)[6] <- 'Navigation_Time'
names(oa_data)[7] <- 'Distance'
names(oa_data)[8] <- 'Speed'
names(oa_data)[9] <- 'Mean_Dwell'
names(oa_data)[10] <- 'Teleportations'
names(oa_data)[11] <- 'Age'
oa_data <- oa_data[ -c(1) ]
oa_data$Block_num <- as.factor(oa_data$Block_num)
sapply(oa_data, class)
oa_data

data <- rbind(ya_data, oa_data)
```

```{r reading more data, include=FALSE}
#This loads the data file as the variable "data"
ya_nav_data <- read.csv('~/Desktop/Research/NPRL/Papers/NavAging_Paper/data_analysis/ya_merged_results.csv')
# Tidying up the data
ya_nav_data<- ya_nav_data %>% mutate(Age = 'YA')
names(ya_nav_data)[1] <- 'index'
names(ya_nav_data)[2] <- 'Participant'
names(ya_nav_data)[3] <- 'Block_num'
names(ya_nav_data)[4] <- 'Target_Name'
names(ya_nav_data)[5] <- 'Total_Time'
names(ya_nav_data)[6] <- 'Orientation_Time'
names(ya_nav_data)[7] <- 'Navigation_Time'
names(ya_nav_data)[8] <- 'Distance'
names(ya_nav_data)[9] <- 'Speed'
names(ya_nav_data)[10] <- 'Mean_Dwell'
names(ya_nav_data)[11] <- 'Teleportations'
names(ya_nav_data)[12] <- 'Age'
ya_nav_data <- ya_nav_data[ -c(1) ]
ya_nav_data$Block_num <- as.factor(ya_nav_data$Block_num)
sapply(ya_nav_data, class)

desired_order <- c("Automobile shop", "Police station ", "Fire Station", "Bank", "Pawn Shop", "Pizzeria", "Quattroki Restaurant", "High School")
# Reorder the levels of Target_Name
ya_nav_data$Target_Name <- factor(ya_nav_data$Target_Name, levels = desired_order)

#This loads the data file as the variable "data"
oa_nav_data <- read.csv('~/Desktop/Research/NPRL/Papers/NavAging_Paper/data_analysis/oa_merged_results.csv')
# Tidying up the data
oa_nav_data<- oa_nav_data %>% mutate(Age = 'OA')
names(oa_nav_data)[1] <- 'index'
names(oa_nav_data)[2] <- 'Participant'
names(oa_nav_data)[3] <- 'Block_num'
names(oa_nav_data)[4] <- 'Target_Name'
names(oa_nav_data)[5] <- 'Total_Time'
names(oa_nav_data)[6] <- 'Orientation_Time'
names(oa_nav_data)[7] <- 'Navigation_Time'
names(oa_nav_data)[8] <- 'Distance'
names(oa_nav_data)[9] <- 'Speed'
names(oa_nav_data)[10] <- 'Mean_Dwell'
names(oa_nav_data)[11] <- 'Teleportations'
names(oa_nav_data)[12] <- 'Age'
oa_nav_data <- oa_nav_data[ -c(1) ]
oa_nav_data$Block_num <- as.factor(oa_nav_data$Block_num)
sapply(oa_nav_data, class)

desired_order <- c("Automobile shop", "Police station ", "Fire Station", "Bank", "Pawn Shop", "Pizzeria", "Quattroki Restaurant", "High School")
# Reorder the levels of Target_Name
oa_nav_data$Target_Name <- factor(oa_nav_data$Target_Name, levels = desired_order)

nav_data <- rbind(ya_nav_data, oa_nav_data)
```

```{r reading more data, include=FALSE}
#This loads the data file as the variable "data"
non_nav_data <- read.csv('~/Desktop/Research/NPRL/Papers/NavAging_Paper/data_analysis/non_nav_data.csv')
# Tidying up the data
names(non_nav_data)[1] <- 'Participant'
names(non_nav_data)[2] <- 'Age'
names(non_nav_data)[3] <- 'PSQI'
names(non_nav_data)[4] <- 'SSS_Pre'
names(non_nav_data)[5] <- 'SSS_Post'
names(non_nav_data)[6] <- 'SBSOD'
names(non_nav_data)[7] <- 'MiniCog'
names(non_nav_data)[8] <- 'TrailsA'
names(non_nav_data)[9] <- 'TrailsB'
names(non_nav_data)[10] <- 'SetShifting'
names(non_nav_data)[11] <- 'CorsiBlocks'
names(non_nav_data)[12] <- 'SSQ_Pre'
names(non_nav_data)[13] <- 'SSQ_Post'
names(non_nav_data)[14] <- 'NARA'
non_nav_data <- select(non_nav_data, -Age) 
```


```{r organizing data, include=FALSE}
b1 <- subset(data, Block_num == 1)
rownames(b1) <- NULL
b2 <- subset(data, Block_num == 2)
rownames(b2) <- NULL 
b3 <- subset(data, Block_num == 3)
rownames(b3) <- NULL 

mean_data <- subset(b3, select = c(Participant, Age))

for (i in 1:nrow(b3)) {
  mean_data$Total_Time[i] <- (b3$Total_Time[i] + b2$Total_Time[i]+b1$Total_Time[i])/3
  mean_data$Orientation_Time[i] <- (b3$Orientation_Time[i] + b2$Orientation_Time[i]+b1$Orientation_Time[i])/3
  mean_data$Navigation_Time[i] <- (b3$Navigation_Time[i] + b2$Navigation_Time[i]+b1$Navigation_Time[i])/3
  mean_data$Distance[i] <- (b3$Distance[i] + b2$Distance[i]+b1$Distance[i])/3
  mean_data$Speed[i] <- (b3$Speed[i] + b2$Speed[i]+b1$Speed[i])/3
  mean_data$Mean_Dwell[i] <- (b3$Mean_Dwell[i] + b2$Mean_Dwell[i]+b1$Mean_Dwell[i])/3
  mean_data$Var_X[i] <- (b3$Var_X[i] + b2$Var_X[i]+b1$Var_X[i])/3
  mean_data$Var_Y[i] <- (b3$Var_Y[i] + b2$Var_Y[i]+b1$Var_Y[i])/3
  mean_data$Var_Z[i] <- (b3$Var_Z[i] + b2$Var_Z[i]+b1$Var_Z[i])/3
  mean_data$Teleportations[i] <- (b3$Teleportations[i] + b2$Teleportations[i]+b1$Teleportations[i])/3
}

mean_data$Age <- factor(mean_data$Age, levels=c("YA", "OA"))

df_merge <- merge(mean_data,non_nav_data,by="Participant") 
ya_data <- df_merge %>%
  filter(Age == "YA")
ya_data <- ya_data %>% mutate(Cohort = 'ya')
oa_data <- df_merge %>%
  filter(Age == "OA")
oa_data$Cohort <- ifelse(oa_data$NARA>50.0, "oa_high", "oa_low")

df_final <- rbind(ya_data, oa_data) 
oa_high <- subset(oa_data, Cohort == "oa_high")
oa_low <- subset(oa_data, Cohort == "oa_low")
ya <- subset(ya_data, Cohort == "ya")
df_final_drop <- select(df_final, c('Participant','Age','NARA', 'Cohort'))
df_final_drop<- df_final_drop[!duplicated(df_final_drop), ]

desired_order <- c("ya", "oa_high", "oa_low")
# Reorder the levels of Target_Name
df_final$Cohort <- factor(df_final$Cohort, levels = desired_order)
```


```{r ct}
#Total_time by Block_num
p_ct <-ggplot(df_final, aes(x = factor(Cohort), y=Total_Time, fill=factor(Cohort))) +
  scale_fill_manual(values =c( 'ya' ='#FF9FAF', 'oa_low' = '#c5b3e2', 'oa_high' = '#7f00ff'))+
  scale_y_continuous(breaks = scales::pretty_breaks(n= 4))+
  ylim (0,168)+
  labs(color= "Cohort", y="Mean Total Time (s)", x="")+
  theme_classic()+
  theme(axis.line = element_line(linewidth = .5, colour = "#242526"))+
  theme(axis.ticks = element_line(linewidth = .2, colour = "#242526"))+
  theme(plot.title = element_text(hjust = 0.5))+
  theme(legend.position = "none")+
  theme(axis.text.x = element_text(size=20))+
  theme(axis.text.y = element_text(size=20))+
  theme(axis.title.y = element_text(size=20))+
  stat_halfeye(
    # adjust bandwidth
    adjust = 0.5,
    # move to the right
    justification = -0.2,
    # remove the slub interval
    .width = 0,
    point_colour = NA,
    scale = 0.5 ##  <(**new parameter**)
  ) +
  geom_boxplot(
    width = 0.12,
    # removing outliers
    outlier.color = NA,
    alpha = 0.5
  )+
  geom_half_point(
    aes(color = Cohort),
    side = 'l',
    range_scale = .4,
    alpha = .3,
    position = position_jitter(seed = 1, width = .12)
  ) +scale_color_manual(values =c( 'ya' ='#FF9FAF', 'oa_low' = '#c5b3e2', 'oa_high' = '#7f00ff'))
p_ct
ggsave(file="~/Desktop/Research/NPRL/Papers/NavAging_Paper/figure_creation/plots/fig8_ct.svg", height = 5, width = 5, plot=p_ct)
```


# Orientation Time

```{r orict}
#Orientation Time by Block_num
p_orict <- ggplot(df_final, aes(x = factor(Cohort), y=Orientation_Time, fill=Cohort)) +
  scale_fill_manual(values =c( 'ya' ='#FF9FAF', 'oa_low' = '#c5b3e2', 'oa_high' = '#7f00ff'))+
  scale_y_continuous(breaks = scales::pretty_breaks(n= 4))+
  ylim (0,30)+
  labs(color= "Cohort", y="Mean Orientation Time (s)", x="")+
  theme_classic()+
  theme(axis.line = element_line(linewidth = .5, colour = "#242526"))+
  theme(axis.ticks = element_line(linewidth = .2, colour = "#242526"))+
  theme(plot.title = element_text(hjust = 0.5))+
  theme(legend.position = "none")+
  theme(axis.text.x = element_text(size=20))+
  theme(axis.text.y = element_text(size=20))+
  theme(axis.title.y = element_text(size=20))+
  # add half-violin from {ggdist} package
  stat_halfeye(
    # adjust bandwidth
    adjust = 0.5,
    # move to the right
    justification = -0.2,
    # remove the slub interval
    .width = 0,
    point_colour = NA,
    scale = 0.5 ##  <(**new parameter**)
  ) +
  geom_boxplot(
    width = 0.12,
    # removing outliers
    outlier.color = NA,
    alpha = 0.5
  )+
  geom_half_point(
    aes(color = Cohort),
    side = 'l',
    range_scale = .4,
    alpha = .3,
    position = position_jitter(seed = 1, width = .12)
  ) + scale_color_manual(values =c( 'ya' ='#FF9FAF', 'oa_low' = '#c5b3e2', 'oa_high' = '#7f00ff'))
p_orict
ggsave(file="~/Desktop/Research/NPRL/Papers/NavAging_Paper/figure_creation/plots/fig8_orict.svg", height = 5, width = 5, plot=p_orict)
```

# Navigation Time

```{r navct}
#Navigation Time by Block_num
p_navct <- ggplot(df_final, aes(x = factor(Cohort), y=Navigation_Time, fill=Cohort)) +
  scale_fill_manual(values =c( 'ya' ='#FF9FAF', 'oa_low' = '#c5b3e2', 'oa_high' = '#7f00ff'))+
  scale_y_continuous(breaks = scales::pretty_breaks(n= 4))+
  ylim (0,168)+
  labs(color= "Cohort", y="Mean Navigation Time (s)", x="")+
  theme_classic()+
  theme(axis.line = element_line(linewidth = .5, colour = "#242526"))+
  theme(axis.ticks = element_line(linewidth = .2, colour = "#242526"))+
  theme(plot.title = element_text(hjust = 0.5))+
  theme(legend.position = "none")+
  theme(axis.text.x = element_text(size=20))+
  theme(axis.text.y = element_text(size=20))+
  theme(axis.title.y = element_text(size=20))+
  # add half-violin from {ggdist} package
  stat_halfeye(
    # adjust bandwidth
    adjust = 0.5,
    # move to the right
    justification = -0.2,
    # remove the slub interval
    .width = 0,
    point_colour = NA,
    scale = 0.5 ##  <(**new parameter**)
  ) +
  geom_boxplot(
    width = 0.12,
    # removing outliers
    outlier.color = NA,
    alpha = 0.5
  )+
  geom_half_point(
    aes(color = Cohort),
    side = 'l',
    range_scale = .4,
    alpha = .3,
    position = position_jitter(seed = 1, width = .12)
  ) + scale_color_manual(values =c( 'ya' ='#FF9FAF', 'oa_low' = '#c5b3e2', 'oa_high' = '#7f00ff'))
p_navct
ggsave(file="~/Desktop/Research/NPRL/Papers/NavAging_Paper/figure_creation/plots/fig8_navct.svg", height = 5, width = 5, plot=p_navct)
```

# Distance

```{r dt}
#Distance by Block_num
p_dt <- ggplot(df_final, aes(x = factor(Cohort), y=Distance, fill=Cohort)) +
  scale_fill_manual(values =c( 'ya' ='#FF9FAF', 'oa_low' = '#c5b3e2', 'oa_high' = '#7f00ff'))+
  scale_y_continuous(breaks = scales::pretty_breaks(n= 4))+
  #ylim (0,160)+
  labs(color= "Cohort", y="Mean Distance Traveled (VR Units)", x="")+
  theme_classic()+
  theme(axis.line = element_line(linewidth = .5, colour = "#242526"))+
  theme(axis.ticks = element_line(linewidth = .2, colour = "#242526"))+
  theme(plot.title = element_text(hjust = 0.5))+
  theme(legend.position = "none")+
  theme(axis.text.x = element_text(size=20))+
  theme(axis.text.y = element_text(size=20))+
  theme(axis.title.y = element_text(size=20))+
  # add half-violin from {ggdist} package
  stat_halfeye(
    # adjust bandwidth
    adjust = 0.5,
    # move to the right
    justification = -0.2,
    # remove the slub interval
    .width = 0,
    point_colour = NA,
    scale = 0.5 ##  <(**new parameter**)
  ) +
  geom_boxplot(
    width = 0.12,
    # removing outliers
    outlier.color = NA,
    alpha = 0.5
  )+
  geom_half_point(
    aes(color = Cohort),
    side = 'l',
    range_scale = .4,
    alpha = .3,
    position = position_jitter(seed = 1, width = .12)
  ) + scale_color_manual(values =c( 'ya' ='#FF9FAF', 'oa_low' = '#c5b3e2', 'oa_high' = '#7f00ff'))
p_dt
ggsave(file="~/Desktop/Research/NPRL/Papers/NavAging_Paper/figure_creation/plots/fig8_dt.svg", height = 5, width = 5, plot=p_dt)
```

# Speed

```{r speed}
#Speed by Block_num
p_speed <- ggplot(df_final, aes(x = factor(Cohort), y=Speed, fill=Cohort)) +
  scale_fill_manual(values =c( 'ya' ='#FF9FAF', 'oa_low' = '#c5b3e2', 'oa_high' = '#7f00ff'))+
  scale_y_continuous(breaks = scales::pretty_breaks(n= 4))+
  ylim(0,30)+
  labs(color= "Cohort", y="Mean Speed (VR Unit/s)", x="")+
  theme_classic()+
  theme(axis.line = element_line(linewidth = .5, colour = "#242526"))+
  theme(axis.ticks = element_line(linewidth = .2, colour = "#242526"))+
  theme(plot.title = element_text(hjust = 0.5))+
  theme(legend.position = "none")+
  theme(axis.text.x = element_text(size=20))+
  theme(axis.text.y = element_text(size=20))+
  theme(axis.title.y = element_text(size=20))+
  # add half-violin from {ggdist} package
  stat_halfeye(
    # adjust bandwidth
    adjust = 0.5,
    # move to the right
    justification = -0.2,
    # remove the slub interval
    .width = 0,
    point_colour = NA,
    scale = 0.5 ##  <(**new parameter**)
  ) +
  geom_boxplot(
    width = 0.12,
    # removing outliers
    outlier.color = NA,
    alpha = 0.5
  )+
  geom_half_point(
    aes(color = Cohort),
    side = 'l',
    range_scale = .4,
    alpha = .3,
    position = position_jitter(seed = 1, width = .12)
  ) + scale_color_manual(values =c( 'ya' ='#FF9FAF', 'oa_low' = '#c5b3e2', 'oa_high' = '#7f00ff'))
p_speed
ggsave(file="~/Desktop/Research/NPRL/Papers/NavAging_Paper/figure_creation/plots/fig8_speed.svg", height = 5, width = 5, plot=p_speed)
```

# Dwell Time

```{r dwell}
#Mean_Dwell by Block_num
p_dwell <- ggplot(df_final, aes(x = factor(Cohort), y=Mean_Dwell, fill=Cohort)) +
  scale_fill_manual(values =c( 'ya' ='#FF9FAF', 'oa_low' = '#c5b3e2', 'oa_high' = '#7f00ff'))+
  labs(color= "Cohort", y="Mean Dwell Time (s)", x="")+
  scale_y_continuous(breaks = scales::pretty_breaks(n= 4))+
  ylim(0,3)+
  theme_classic()+
  theme(axis.line = element_line(linewidth = .5, colour = "#242526"))+
  theme(axis.ticks = element_line(linewidth = .2, colour = "#242526"))+
  theme(plot.title = element_text(hjust = 0.5))+
  theme(legend.position = "none")+
  theme(axis.text.x = element_text(size=20))+
  theme(axis.text.y = element_text(size=20))+
  theme(axis.title.y = element_text(size=20))+
  # add half-violin from {ggdist} package
  stat_halfeye(
    # adjust bandwidth
    adjust = 0.5,
    # move to the right
    justification = -0.2,
    # remove the slub interval
    .width = 0,
    point_colour = NA,
    scale = 0.5 ##  <(**new parameter**)
  ) +
  geom_boxplot(
    width = 0.12,
    # removing outliers
    outlier.color = NA,
    alpha = 0.5
  )+
  geom_half_point(
    aes(color = Cohort),
    side = 'l',
    range_scale = .4,
    alpha = .3,
    position = position_jitter(seed = 1, width = .12)
  )+ scale_color_manual(values =c( 'ya' ='#FF9FAF', 'oa_low' = '#c5b3e2', 'oa_high' = '#7f00ff'))
p_dwell
ggsave(file="~/Desktop/Research/NPRL/Papers/NavAging_Paper/figure_creation/plots/fig8_dwell.svg", height = 5, width = 5, plot=p_dwell)
``` 

# Teleportations

```{r teleport}
#Teleportations by Block_num
p_teleport <- ggplot(df_final, aes(x = factor(Cohort), y=Teleportations, fill=Cohort)) +
  scale_fill_manual(values =c( 'ya' ='#FF9FAF', 'oa_low' = '#c5b3e2', 'oa_high' = '#7f00ff'))+
  scale_y_continuous(breaks = scales::pretty_breaks(n= 4))+
  ylim(0,150)+
  labs(color= "Cohort", y="Mean Teleportations (count)", x="")+
  theme_classic()+
  theme(axis.line = element_line(linewidth = .5, colour = "#242526"))+
  theme(axis.ticks = element_line(linewidth = .2, colour = "#242526"))+
  theme(plot.title = element_text(hjust = 0.5))+
  theme(legend.position = "none")+
  theme(axis.text.x = element_text(size=20))+
  theme(axis.text.y = element_text(size=20))+
  theme(axis.title.y = element_text(size=20))+
  # add half-violin from {ggdist} package
  stat_halfeye(
    # adjust bandwidth
    adjust = 0.5,
    # move to the right
    justification = -0.2,
    # remove the slub interval
    .width = 0,
    point_colour = NA,
    scale = 0.5 ##  <(**new parameter**)
  ) +
  geom_boxplot(
    width = 0.12,
    # removing outliers
    outlier.color = NA,
    alpha = 0.5
  )+
  geom_half_point(
    aes(color = Cohort),
    side = 'l',
    range_scale = .4,
    alpha = .3,
    position = position_jitter(seed = 1, width = .12)
  ) + scale_color_manual(values =c( 'ya' ='#FF9FAF', 'oa_low' = '#c5b3e2', 'oa_high' = '#7f00ff'))
p_teleport
ggsave(file="~/Desktop/Research/NPRL/Papers/NavAging_Paper/figure_creation/plots/fig8_teleport.svg", height = 5, width = 5, plot=p_teleport)
```

```{r fig8, fig.height = 16, fig.width = 20, fig.align = "center"}
p<-grid.arrange(p_speed, p_ct, p_orict, p_navct, p_dt, p_dwell, p_teleport, ncol=4, nrow=3)
ggsave(file="~/Desktop/Research/NPRL/Papers/NavAging_Paper/figure_creation/plots/composite_fig8.svg", height = 16, width =20, plot=p)

```

