---
title: "ymaze_class_vs_NARA"
output: html_document
date: "2024-08-05"
---

```{r global-options, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, warning=FALSE, message=FALSE)
```

```{r}
#install.packages("readr")
#install.packages("dplyr")
#install.packages("tidyverse")
#install.packages("ggplot2")
#install.packages("ggpubr", "broom", "AICcmodavg")
```

```{r}
library(readr)
library(dplyr)
library(tidyverse)
library(ggplot2)
#library(ggpubr)
#library(broom)
#library(AICcmodavg)
```

```{r}
#This loads the data file as the variable "data"
non_nav_data <- read.csv('/Users/emilycui/Desktop/NPRL (RS)/NAVIGATION/NavAging_Paper/data_analysis/non_nav_data.csv')
# Tidying up the data
names(non_nav_data)[1] <- 'Participant'
names(non_nav_data)[2] <- 'Age'
names(non_nav_data)[3] <- 'PSQI'
names(non_nav_data)[4] <- 'SSS_Pre'
names(non_nav_data)[5] <- 'SSS_Post'
names(non_nav_data)[6] <- 'SBSOD'
names(non_nav_data)[7] <- 'MiniCog'
names(non_nav_data)[8] <- 'TrailsA'
names(non_nav_data)[9] <- 'TrailsB'
names(non_nav_data)[10] <- 'SetShifting'
names(non_nav_data)[11] <- 'CorsiBlocks'
names(non_nav_data)[12] <- 'SSQ_Pre'
names(non_nav_data)[13] <- 'SSQ_Post'
names(non_nav_data)[14] <- 'NARA'
non_nav_data <- select(non_nav_data, -Age) 

#Deleting the participants who did not complete the Y-Maze (BNC1-20)
non_nav_data <- non_nav_data[-c(1:20),]
```

```{r}
# Filtering Ego Pres Data
ymaze_ego <- non_nav_data %>% filter(ymaze_class == 'ego')
ymaze_allo <- non_nav_data %>% filter(ymaze_class == 'allo')
```

```{r}
NARA_ymaze_class_age <- ggplot(non_nav_data, aes(x=ymaze_class_age_presence, y=NARA, color=nara_class))+
 geom_point(size=4)+
  stat_summary(fun.args = list(mult=1), 
                geom="crossbar", 
                width=0.2, 
                color="black")+
  labs(color= "Participant", y="NARA", x="Age-Reference Frame")+
  scale_x_discrete("Age-YMaze Class",limits = c("YA-allo","YA-ego","OA-allo","OA-ego"))+
  scale_color_manual(values =c( 'YA' ='#FF9FAF', 'OA-low' = '#9dff00', 'OA-high' = '#5E7AFA'))+
  ggtitle("X")

NARA_ymaze_class_age
```

```{r}
NARA_ymaze_oa <- ggplot(non_nav_data, aes(x=ymaze_class_oa_presence, y=NARA, color=nara_class))+
 geom_point(size=4)+
  stat_summary(fun.args = list(mult=1), 
                geom="crossbar", 
                width=0.2, 
                color="black")+
  labs(color= "Participant", y="NARA", x="Age-Reference Frame")+
  scale_x_discrete("Age-YMaze Class OA",limits = c("YA","OA-allo","OA-ego"))+
  scale_color_manual(values =c( 'YA' ='#FF9FAF', 'OA-low' = '#9dff00', 'OA-high' = '#5E7AFA'))+
  ggtitle("X")

NARA_ymaze_oa 
```

```{r}
NARA_ymaze_class <- ggplot(non_nav_data, aes(x=ymaze_class, y=NARA, color=nara_class))+
 geom_point(size=4)+
  stat_summary(fun.args = list(mult=1), 
                geom="crossbar", 
                width=0.2, 
                color="black")+
  labs(color= "Participant", y="NARA", x="Age-Reference Frame")+
  scale_x_discrete("Y-Maze Class",limits = c("ego","allo"))+
  scale_color_manual(values =c( 'YA' ='#FF9FAF', 'OA-low' = '#9dff00', 'OA-high' = '#5E7AFA'))+
  ggtitle("X")

NARA_ymaze_class
```

```{r}
# T-Test for Ego vs. Allo NARA scores
ttest_ymaze_class_nara <- t.test(ymaze_ego$NARA, ymaze_allo$NARA, p.adjust="none")

ttest_ymaze_class_nara
```



