---
title: "Figure 2 Stats Code"
output: html_document
date: "2023-05-13"
---


```{r global-options, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, warning=FALSE, message=FALSE)
```

```{r loading libraries, include=FALSE}

# This code chunk loads various libraries necessary to complete the data analysis and produce graphics
library(tidyverse)
library(stringr)
library(ez)
library(cowplot)
library(viridis)
library(viridisLite)
library("readxl")
library("ggcorrplot")
library(dplyr)
library(ltm)
library(plotrix)
library("viridis")
library("paletteer")
library(ggpubr)
library(rstatix)
library(lme4)
library(lmerTest)
library('emmeans')
```

```{r reading data, include=FALSE}
#This data chunk loads and tidies up the data

#This loads the data file as the variable "ya_data"
# ya_data <- read.csv('/Users/yasminebassil/Documents/Emory/3_Research/Projects/NavAging_Paper/data/ya_averaged_results.csv')

# AP loading data
#ya_data <- read.csv('/Users/ashleypelton/Documents/NPRL/NavAging_Paper/data/ya_averaged_results.csv')

# YB loading data
ya_data <- read.csv('/Users/yasminebassil/Documents/Emory/3_Research/Projects/NavAging_Paper/data/ya_averaged_results.csv')

# Tidying up the data
names(ya_data)[1] <- 'index'
names(ya_data)[2] <- 'Participant'
names(ya_data)[3] <- 'Block_num'
names(ya_data)[4] <- 'Total_Time'
names(ya_data)[5] <- 'Orientation_Time'
names(ya_data)[6] <- 'Navigation_Time'
names(ya_data)[7] <- 'Distance'
names(ya_data)[8] <- 'Speed'
names(ya_data)[9] <- 'Mean_Dwell'
names(ya_data)[10] <- 'Teleportations'
ya_data <- ya_data[ -c(1) ]
ya_data$Block_num <- as.factor(ya_data$Block_num)
sapply(ya_data, class)
ya_data$Age <- "YA"
ya_data
```

```{r reading data 2, include=FALSE}
#This data chunk loads and tidies up the data

#This loads the data file as the variable "ya_data"
# oa_data <- read.csv('/Users/yasminebassil/Documents/Emory/3_Research/Projects/NavAging_Paper/data/oa_averaged_results.csv')

# AP loading data
#oa_data <- read.csv('/Users/ashleypelton/Documents/NPRL/NavAging_Paper/data/oa_averaged_results.csv')

# YB loading data
oa_data <- read.csv('/Users/yasminebassil/Documents/Emory/3_Research/Projects/NavAging_Paper/data/oa_averaged_results.csv')

# Tidying up the data
names(oa_data)[1] <- 'index'
names(oa_data)[2] <- 'Participant'
names(oa_data)[3] <- 'Block_num'
names(oa_data)[4] <- 'Total_Time'
names(oa_data)[5] <- 'Orientation_Time'
names(oa_data)[6] <- 'Navigation_Time'
names(oa_data)[7] <- 'Distance'
names(oa_data)[8] <- 'Speed'
names(oa_data)[9] <- 'Mean_Dwell'
names(oa_data)[10] <- 'Teleportations'
oa_data <- oa_data[ -c(1) ]
oa_data$Block_num <- as.factor(oa_data$Block_num)
sapply(oa_data, class)
oa_data$Age <- "OA"
oa_data
```

```{r}
all_data <- rbind(ya_data, oa_data)
```


```{r reading more data, include=FALSE}
#This loads the data file as the variable "ya_target_data"
# ya_target_data <- read.csv('/Users/yasminebassil/Documents/Emory/3_Research/Projects/NavAging_Paper/data/ya_merged_results.csv')

# AP loading data
#ya_target_data <- read.csv('/Users/ashleypelton/Documents/NPRL/NavAging_Paper/data/ya_merged_results.csv')

# YB loading data
ya_target_data <- read.csv('/Users/yasminebassil/Documents/Emory/3_Research/Projects/NavAging_Paper/data/ya_merged_results.csv')

# Tidying up the data
names(ya_target_data)[1] <- 'index'
names(ya_target_data)[2] <- 'Participant'
names(ya_target_data)[3] <- 'Block_num'
names(ya_target_data)[4] <- 'Target_Name'
names(ya_target_data)[5] <- 'Total_Time'
names(ya_target_data)[6] <- 'Orientation_Time'
names(ya_target_data)[7] <- 'Navigation_Time'
names(ya_target_data)[8] <- 'Distance'
names(ya_target_data)[9] <- 'Speed'
names(ya_target_data)[10] <- 'Mean_Dwell'
names(ya_target_data)[11] <- 'Teleportations'
ya_target_data <- ya_target_data[ -c(1) ]
ya_target_data$Block_num <- as.factor(ya_target_data$Block_num)
sapply(ya_target_data, class)

desired_order <- c("Automobile shop", "Police station ", "Fire Station", "Bank", "Pawn Shop", "Pizzeria", "Quattroki Restaurant", "High School")
# Reorder the levels of Target_Name
ya_target_data$Target_Name <- factor(ya_target_data$Target_Name, levels = desired_order)
ya_target_data$Age <- "YA"
```

```{r reading more data 2, include=FALSE}
#This loads the data file as the variable "oa_target_data"
# oa_target_data <- read.csv('/Users/yasminebassil/Documents/Emory/3_Research/Projects/NavAging_Paper/data/oa_merged_results.csv')

# AP loading data
#oa_target_data <- read.csv('/Users/ashleypelton/Documents/NPRL/NavAging_Paper/data/oa_merged_results.csv')

# YB loading data
oa_target_data <- read.csv('/Users/yasminebassil/Documents/Emory/3_Research/Projects/NavAging_Paper/data/oa_merged_results.csv')


# Tidying up the data
names(oa_target_data)[1] <- 'index'
names(oa_target_data)[2] <- 'Participant'
names(oa_target_data)[3] <- 'Block_num'
names(oa_target_data)[4] <- 'Target_Name'
names(oa_target_data)[5] <- 'Total_Time'
names(oa_target_data)[6] <- 'Orientation_Time'
names(oa_target_data)[7] <- 'Navigation_Time'
names(oa_target_data)[8] <- 'Distance'
names(oa_target_data)[9] <- 'Speed'
names(oa_target_data)[10] <- 'Mean_Dwell'
names(oa_target_data)[11] <- 'Teleportations'
oa_target_data <- oa_target_data[ -c(1) ]
oa_target_data$Block_num <- as.factor(oa_target_data$Block_num)
sapply(oa_target_data, class)

# Reorder the levels of Target_Name
oa_target_data$Target_Name <- factor(oa_target_data$Target_Name, levels = desired_order)
oa_target_data$Age <- "OA"
```

```{r}
all_target_data <- rbind(ya_target_data, oa_target_data)
```

# ANOVA - All Values

```{r}
# This runs ANOVA tests for all outcome measures
outcome_measures <- c('Total_Time', 'Orientation_Time', 'Navigation_Time', 'Distance', 'Speed', 'Mean_Dwell', 'Teleportations')

for (outcome in outcome_measures) {
  anova_formula <- as.formula(paste(outcome, "~ Age"))
  ct_anova <- aov(anova_formula, data = all_data)
  
  assign(paste0(outcome, "_ANOVA"), ct_anova)
  
  cat("\nANOVA for", outcome, ":\n")
  print(summary(ct_anova))
}
# omnibus p-values - main effect of this variable
```