---
title: "Figure 4 Stats Code"
output: html_document
date: "2023-05-13"
---


```{r global-options, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, warning=FALSE, message=FALSE)
```

```{r}
# Clearing environment
rm(list = ls())
```

```{r loading libraries, include=FALSE}
# This code chunk loads various libraries necessary to complete the data analysis and produce graphics
library(tidyverse)
library(stringr)
library(ez)
library(cowplot)
library(viridis)
library(viridisLite)
library("readxl")
library("ggcorrplot")
library(dplyr)
library(ltm)
library(plotrix)
library("viridis")
library("paletteer")
library(ggpubr)
library(rstatix)
library(lme4)
#install.packages("lmerTest")
library(lmerTest)
#install.packages('emmeans')
library('emmeans')
```

```{r reading data, include=FALSE}
#This data chunk loads and tidies up the data

#This loads the data file as the variable "ya_data"
ya_data <- read.csv('/Users/yasminebassil/Documents/Emory/3_Research/Projects/NavAging_Paper/data/ya_averaged_results.csv')
# Tidying up the data
names(ya_data)[1] <- 'index'
names(ya_data)[2] <- 'Participant'
names(ya_data)[3] <- 'Block_num'
names(ya_data)[4] <- 'Total_Time'
names(ya_data)[5] <- 'Orientation_Time'
names(ya_data)[6] <- 'Navigation_Time'
names(ya_data)[7] <- 'Distance'
names(ya_data)[8] <- 'Speed'
names(ya_data)[9] <- 'Mean_Dwell'
names(ya_data)[10] <- 'Teleportations'
ya_data <- ya_data[ -c(1) ]
ya_data$Block_num <- as.factor(ya_data$Block_num)
sapply(ya_data, class)
ya_data$Age <- "YA"
ya_data
```

```{r reading data, include=FALSE}
#This data chunk loads and tidies up the data

#This loads the data file as the variable "ya_data"
oa_data <- read.csv('/Users/yasminebassil/Documents/Emory/3_Research/Projects/NavAging_Paper/data/oa_averaged_results.csv')
# Tidying up the data
names(oa_data)[1] <- 'index'
names(oa_data)[2] <- 'Participant'
names(oa_data)[3] <- 'Block_num'
names(oa_data)[4] <- 'Total_Time'
names(oa_data)[5] <- 'Orientation_Time'
names(oa_data)[6] <- 'Navigation_Time'
names(oa_data)[7] <- 'Distance'
names(oa_data)[8] <- 'Speed'
names(oa_data)[9] <- 'Mean_Dwell'
names(oa_data)[10] <- 'Teleportations'
oa_data <- oa_data[ -c(1) ]
oa_data$Block_num <- as.factor(oa_data$Block_num)
sapply(oa_data, class)
oa_data$Age <- "OA"
oa_data
```

```{r}
all_data <- rbind(ya_data, oa_data)
```


```{r reading more data, include=FALSE}
#This loads the data file as the variable "ya_target_data"
ya_target_data <- read.csv('/Users/yasminebassil/Documents/Emory/3_Research/Projects/NavAging_Paper/data/ya_merged_results.csv')
# Tidying up the data
names(ya_target_data)[1] <- 'index'
names(ya_target_data)[2] <- 'Participant'
names(ya_target_data)[3] <- 'Block_num'
names(ya_target_data)[4] <- 'Target_Name'
names(ya_target_data)[5] <- 'Total_Time'
names(ya_target_data)[6] <- 'Orientation_Time'
names(ya_target_data)[7] <- 'Navigation_Time'
names(ya_target_data)[8] <- 'Distance'
names(ya_target_data)[9] <- 'Speed'
names(ya_target_data)[10] <- 'Mean_Dwell'
names(ya_target_data)[11] <- 'Teleportations'
ya_target_data <- ya_target_data[ -c(1) ]
ya_target_data$Block_num <- as.factor(ya_target_data$Block_num)
sapply(ya_target_data, class)

desired_order <- c("Automobile shop", "Police station ", "Fire Station", "Bank", "Pawn Shop", "Pizzeria", "Quattroki Restaurant", "High School")
# Reorder the levels of Target_Name
ya_target_data$Target_Name <- factor(ya_target_data$Target_Name, levels = desired_order)
ya_target_data$Age <- "YA"
```

```{r reading more data, include=FALSE}
#This loads the data file as the variable "oa_target_data"
oa_target_data <- read.csv('/Users/yasminebassil/Documents/Emory/3_Research/Projects/NavAging_Paper/data/oa_merged_results.csv')
# Tidying up the data
names(oa_target_data)[1] <- 'index'
names(oa_target_data)[2] <- 'Participant'
names(oa_target_data)[3] <- 'Block_num'
names(oa_target_data)[4] <- 'Target_Name'
names(oa_target_data)[5] <- 'Total_Time'
names(oa_target_data)[6] <- 'Orientation_Time'
names(oa_target_data)[7] <- 'Navigation_Time'
names(oa_target_data)[8] <- 'Distance'
names(oa_target_data)[9] <- 'Speed'
names(oa_target_data)[10] <- 'Mean_Dwell'
names(oa_target_data)[11] <- 'Teleportations'
oa_target_data <- oa_target_data[ -c(1) ]
oa_target_data$Block_num <- as.factor(oa_target_data$Block_num)
sapply(oa_target_data, class)

# Reorder the levels of Target_Name
oa_target_data$Target_Name <- factor(oa_target_data$Target_Name, levels = desired_order)
oa_target_data$Age <- "OA"
```

```{r}
all_target_data <- rbind(ya_target_data, oa_target_data)
```

# Using All Target Data (Across Age Groups)

```{r}
# This runs ANOVA tests for all outcome measures
outcome_measures <- c('Total_Time', 'Orientation_Time', 'Navigation_Time', 'Distance', 'Speed', 'Mean_Dwell', 'Teleportations')
outcome_names <- c('ct', 'orict','navct','dt','speed', 'dwell', 'teleport')
count <- 1

# Looping through outcome measures
for (outcome in outcome_measures) {
  
  # Running the linear mixed model (LMM)
  lmm_formula <- as.formula(paste(outcome, "~ Block_num*Target_Name*Age + (1|Participant)"))
  lmm_outcome <- lmer(lmm_formula, data = all_target_data)
  assign(paste0("m_",outcome_names[count]), lmm_outcome)
  
  # Running the anova on the LMM
  anova_formula <- paste0("m_",outcome_names[count])
  anova <- anova(get(paste0("m_",outcome_names[count])))
  assign(paste0("m_",outcome_names[count], "_anova"), anova)
  
  # Printing all anova outputs
  cat("\nANOVA for", outcome, ":\n")
  print(anova)
  
  # Running contrasts on LMM for BLOCK
  contrast_b <- emmeans(get(paste0("m_",outcome_names[count])), ~Block_num)
  assign(paste0("emm_m_",outcome_names[count], "_b"), contrast_b)
  
  # Running pairs on contrast
  emm_pairs_b <- pairs(get(paste0("emm_m_",outcome_names[count], "_b")))
  emm_pairs_b <- as.data.frame(emm_pairs_b)
  assign(paste0("m_", outcome_names[count], "_block"), emm_pairs_b)
  
  # Running contrasts on LMM for TARGET
  contrast_t <- emmeans(get(paste0("m_",outcome_names[count])), ~Target_Name)
  assign(paste0("emm_m_",outcome_names[count], "_t"), contrast_t)
  
  # Running pairs on contrast
  emm_pairs_t <- pairs(get(paste0("emm_m_",outcome_names[count], "_t")))
  emm_pairs_t <- as.data.frame(emm_pairs_t)
  assign(paste0("m_", outcome_names[count], "_targetonly"), emm_pairs_t)
  
  # Running contrasts on LMM for BLOCK:TARGET interaction
  contrast_bt <- emmeans(get(paste0("m_",outcome_names[count])), ~Block_num|Target_Name)
  assign(paste0("emm_m_",outcome_names[count]), contrast_bt)
  
  # Running pairs on contrast
  emm_pairs_bt <- pairs(get(paste0("emm_m_",outcome_names[count])))
  emm_pairs_bt <- as.data.frame(emm_pairs_bt)
  assign(paste0("m_", outcome_names[count], "_blocktarget"), emm_pairs_bt)
  
  # Updating count variable to loop through outcome names
  count <- count + 1
}
```


```{r}
rm("anova")

# List all dataframes in the global environment
dataframes <- ls()

# Filter dataframes that end with "anova"
dataframes_to_save_anova <- dataframes[grep("anova$", dataframes)]

# Create an empty list to store dataframes
combined_dataframes_anova <- list()

# Loop through the selected dataframes, combine them, and add a "Source" column
for (df_name in dataframes_to_save_anova) {
  # Get the dataframe by name
  df <- get(df_name)
  
  # Add a "Source" column with the dataframe name
  df$Source <- df_name
  
  # Append the modified dataframe to the list
  combined_dataframes_anova[[df_name]] <- df
}

# Combine all dataframes into one giant dataframe
final_combined_dataframe_anova <- do.call(rbind, combined_dataframes_anova)

# Specify the directory where you want to save the CSV file
output_directory <- "/Users/yasminebassil/Documents/Emory/3_Research/Projects/NavAging_Paper/stat_tests/"

# Define the CSV file name
csv_file <- paste0(output_directory, "all_anova_data.csv")

# Save the combined dataframe as a CSV file
write.csv(final_combined_dataframe_anova, file = csv_file, row.names = TRUE)

# Print a message to confirm the save
cat("Saved combined data as", csv_file, "\n")

```


```{r}

# List all dataframes in the global environment
dataframes <- ls()

# Filter dataframes that end with "anova"
dataframes_to_save_block <- dataframes[grep("block$", dataframes)]

# Create an empty list to store dataframes
combined_dataframes_block <- list()

# Loop through the selected dataframes, combine them, and add a "Source" column
for (df_name in dataframes_to_save_block) {
  # Get the dataframe by name
  df <- get(df_name)
  
  # Add a "Source" column with the dataframe name
  df$Source <- df_name
  
  # Append the modified dataframe to the list
  combined_dataframes_block[[df_name]] <- df
}

# Combine all dataframes into one giant dataframe
final_combined_dataframe_block <- do.call(rbind, combined_dataframes_block)

# Specify the directory where you want to save the CSV file
output_directory <- "/Users/yasminebassil/Documents/Emory/3_Research/Projects/NavAging_Paper/stat_tests/"

# Define the CSV file name
csv_file <- paste0(output_directory, "all_block_data.csv")

# Save the combined dataframe as a CSV file
write.csv(final_combined_dataframe_block, file = csv_file, row.names = TRUE)

# Print a message to confirm the save
cat("Saved combined data as", csv_file, "\n")

```



```{r}

# List all dataframes in the global environment
dataframes2 <- ls()

# Filter dataframes that end with "anova"
dataframes_to_save_blocktarget <- dataframes2[grep("blocktarget$", dataframes2)]

# Create an empty list to store dataframes
combined_dataframes_blocktarget <- list()

# Loop through the selected dataframes, combine them, and add a "Source" column
for (df_name in combined_dataframes_blocktarget) {
  # Get the dataframe by name
  df <- get(df_name)
  
  # Add a "Source" column with the dataframe name
  df$Source <- df_name
  
  # Append the modified dataframe to the list
  combined_dataframes_blocktarget[[df_name]] <- df
}

# Combine all dataframes into one giant dataframe
final_combined_dataframe_blocktarget <- do.call(rbind, combined_dataframes_blocktarget)

# Specify the directory where you want to save the CSV file
output_directory <- "/Users/yasminebassil/Documents/Emory/3_Research/Projects/NavAging_Paper/stat_tests/"

# Define the CSV file name
csv_file <- paste0(output_directory, "all_blocktarget_data.csv")

# Save the combined dataframe as a CSV file
write.csv(final_combined_dataframe_blocktarget, file = csv_file, row.names = TRUE)

# Print a message to confirm the save
cat("Saved combined data as", csv_file, "\n")
```


```{r}

# List all dataframes in the global environment
dataframes3 <- ls()

# Filter dataframes that end with "anova"
dataframes_to_save_targetonly <- dataframes3[grep("targetonly$", dataframes3)]

# Create an empty list to store dataframes
combined_dataframes_targetonly <- list()

# Loop through the selected dataframes, combine them, and add a "Source" column
for (df_name in dataframes_to_save_targetonly) {
  # Get the dataframe by name
  df <- get(df_name)
  
  # Add a "Source" column with the dataframe name
  df$Source <- df_name
  
  # Append the modified dataframe to the list
  combined_dataframes_targetonly[[df_name]] <- df
}

# Combine all dataframes into one giant dataframe
final_combined_dataframe_targetonly <- do.call(rbind, combined_dataframes_targetonly)

# Specify the directory where you want to save the CSV file
output_directory <- "/Users/yasminebassil/Documents/Emory/3_Research/Projects/NavAging_Paper/stat_tests/"

# Define the CSV file name
csv_file <- paste0(output_directory, "all_target_data.csv")

# Save the combined dataframe as a CSV file
write.csv(final_combined_dataframe_targetonly, file = csv_file, row.names = TRUE)

# Print a message to confirm the save
cat("Saved combined data as", csv_file, "\n")
```


# Creating Figure 4 P-Value Matrices

```{r}
unique_labels <- unique(final_combined_dataframe_targetonly$Source)

for (source_label in unique_labels) {
  # Filter the dataset based on the label
  filtered_data <- subset(final_combined_dataframe_targetonly, Source == source_label)
  filtered_data[, 8] <- filtered_data[, 6] * 7
  colnames(filtered_data)[8] <- "p.value.adj"
  filtered_data <- separate(filtered_data, contrast, into = c("t1", "t2"), sep = " - ")
  filtered_data$p.value.adj[filtered_data$p.value.adj > 1] <- 1
  filtered_data$t1 <- factor(filtered_data$t1, 
                                  levels = c("Automobile shop", "Police station ", 
                                             "Fire Station", "Bank", "Pawn Shop",
                                             "Pizzeria", "Quattroki Restaurant",
                                             "High School"))
  filtered_data$t2 <- factor(filtered_data$t2, 
                                  levels = c("Automobile shop", "Police station ", 
                                             "Fire Station", "Bank", "Pawn Shop",
                                             "Pizzeria", "Quattroki Restaurant",
                                             "High School"))
  
  new <- data.frame()
  for (i in 1:nrow(filtered_data)) {
    if (filtered_data$t1[i] == "Automobile shop" | filtered_data$t2[i] == "High School") {
      new <- rbind(new, filtered_data[i, ])
    }
  }
  
  
  temp <- new$t1
  new$t1 <- new$t2
  new$t2 <- temp
  combined <- rbind(filtered_data, new)
  
  combined <- combined[!(combined$t1 == "Police station " & combined$t2 == "Automobile shop"), ]
  combined <- combined[!(combined$t1 == "Fire Station" & combined$t2 == "Automobile shop"), ]
  combined <- combined[!(combined$t1 == "Bank" & combined$t2 == "Automobile shop"), ]
  combined <- combined[!(combined$t1 == "Pawn Shop" & combined$t2 == "Automobile shop"), ]
  combined <- combined[!(combined$t1 == "Pizzeria" & combined$t2 == "Automobile shop"), ]
  combined <- combined[!(combined$t1 == "Quattroki Restaurant" & combined$t2 == "Automobile shop"), ]
  combined <- combined[!(combined$t1 == "High School" & combined$t2 == "Automobile shop"), ]
  combined <- combined[!(combined$t1 == "High School" & combined$t2 == "Police station "), ]
  combined <- combined[!(combined$t1 == "High School" & combined$t2 == "Fire Station"), ]
  combined <- combined[!(combined$t1 == "High School" & combined$t2 == "Bank"), ]
  combined <- combined[!(combined$t1 == "High School" & combined$t2 == "Pawn Shop"), ]
  combined <- combined[!(combined$t1 == "High School" & combined$t2 == "Pizzeria"), ]
  combined <- combined[!(combined$t1 == "High School" & combined$t2 == "Quattroki Restaurant"), ]
  
  new_rows <- data.frame(
    t1 = c("Automobile shop", "Police station ", "Fire Station", "Bank", "Pawn Shop", "Pizzeria", 
           "Quattroki Restaurant", "High School"),
    t2 = c("Automobile shop", "Police station ", "Fire Station", "Bank", "Pawn Shop", "Pizzeria", 
           "Quattroki Restaurant", "High School"),
    estimate = c(rep(1, times = 8)),
    SE = c(rep(1, times = 8)),
    df = c(rep(1, times = 8)),
    t.ratio = c(rep(1, times = 8)),
    p.value = c(rep(1, times = 8)),
    Source = c(rep(source_label, times = 8)),
    p.value.adj = c(rep(1, times = 8))
    )
  
 
  new_combined <- rbind(combined, new_rows)
  
  # Assign filtered data to a new data frame with the label name
  assign(paste0("data_", source_label), new_combined)
}
```
  

## Creating Heatmaps

```{r}
heatmap_speed <- ggplot(data_m_speed_targetonly, aes(x = t1, y = t2, fill = p.value.adj)) +
  geom_tile(aes(width = 1, height = 1), color = "white", lwd = 1) +
  geom_tile(data = subset(data_m_speed_targetonly, p.value.adj < 0.05), aes(width = 1, height = 1), 
            color = "white", lwd = 1) +
  geom_text(aes(label = ifelse(p.value.adj < 0.05, "*", ""), 
                fontface = ifelse(p.value.adj <0.05, "bold", "plain")),
            size = 10, vjust = 0.7, hjust = 0.5, color = "white") +
  scale_fill_gradient(limits = c(0,0.05), low = "#800971", high = "#EDACE5", na.value = "#ffd2d9") +
  labs(title = "", x = "", y = "", fill = "P-Value") +
  theme_classic() +
  theme(axis.line = element_line(linewidth = .5, colour = "#242526")) +
  theme(axis.ticks = element_line(linewidth = .2, colour = "#242526")) +
  theme(plot.title = element_text(hjust = 0.5)) +
  theme(legend.position = "right") +
  theme(axis.text.x = element_text(size=25)) +
  theme(axis.text.y = element_text(size=25)) +
  scale_x_discrete(labels=c("T1","T2","T3","T4","T5","T6","T7","T8")) +
  scale_y_discrete(labels=c("T1","T2","T3","T4","T5","T6","T7","T8"))
heatmap_speed
```


```{r}
heatmap_ct <- ggplot(data_m_ct_targetonly, aes(x = t1, y = t2, fill = p.value.adj)) +
  geom_tile(aes(width = 1, height = 1), color = "white", lwd = 1) +
  geom_tile(data = subset(data_m_ct_targetonly, p.value.adj < 0.05), aes(width = 1, height = 1), 
            color = "white", lwd = 1) +
  geom_text(aes(label = ifelse(p.value.adj < 0.05, "*", ""), 
                fontface = ifelse(p.value.adj <0.05, "bold", "plain")),
            size = 10, vjust = 0.7, hjust = 0.5, color = "white") +
  scale_fill_gradient(limits = c(0,0.05), low = "#800971", high = "#EDACE5", na.value = "#ffd2d9") +
  labs(title = "", x = "", y = "", fill = "P-Value") +
  theme_classic() +
  theme(axis.line = element_line(linewidth = .5, colour = "#242526")) +
  theme(axis.ticks = element_line(linewidth = .2, colour = "#242526")) +
  theme(plot.title = element_text(hjust = 0.5)) +
  theme(legend.position = "right") +
  theme(axis.text.x = element_text(size=25)) +
  theme(axis.text.y = element_text(size=25)) +
  scale_x_discrete(labels=c("T1","T2","T3","T4","T5","T6","T7","T8")) +
  scale_y_discrete(labels=c("T1","T2","T3","T4","T5","T6","T7","T8"))
heatmap_ct
```


```{r}
heatmap_orict <- ggplot(data_m_orict_targetonly, aes(x = t1, y = t2, fill = p.value.adj)) +
  geom_tile(aes(width = 1, height = 1), color = "white", lwd = 1) +
  geom_tile(data = subset(data_m_orict_targetonly, p.value.adj < 0.05), aes(width = 1, height = 1), 
            color = "white", lwd = 1) +
  geom_text(aes(label = ifelse(p.value.adj < 0.05, "*", ""), 
                fontface = ifelse(p.value.adj <0.05, "bold", "plain")),
            size = 10, vjust = 0.7, hjust = 0.5, color = "white") +
  scale_fill_gradient(limits = c(0,0.05), low = "#800971", high = "#EDACE5", na.value = "#ffd2d9") +
  labs(title = "", x = "", y = "", fill = "P-Value") +
  theme_classic() +
  theme(axis.line = element_line(linewidth = .5, colour = "#242526")) +
  theme(axis.ticks = element_line(linewidth = .2, colour = "#242526")) +
  theme(plot.title = element_text(hjust = 0.5)) +
  theme(legend.position = "right") +
  theme(axis.text.x = element_text(size=25)) +
  theme(axis.text.y = element_text(size=25)) +
  scale_x_discrete(labels=c("T1","T2","T3","T4","T5","T6","T7","T8")) +
  scale_y_discrete(labels=c("T1","T2","T3","T4","T5","T6","T7","T8"))
heatmap_orict
```

```{r}
heatmap_navct <- ggplot(data_m_navct_targetonly, aes(x = t1, y = t2, fill = p.value.adj)) +
  geom_tile(aes(width = 1, height = 1), color = "white", lwd = 1) +
  geom_tile(data = subset(data_m_navct_targetonly, p.value.adj < 0.05), aes(width = 1, height = 1), 
            color = "white", lwd = 1) +
  geom_text(aes(label = ifelse(p.value.adj < 0.05, "*", ""), 
                fontface = ifelse(p.value.adj <0.05, "bold", "plain")),
            size = 10, vjust = 0.7, hjust = 0.5, color = "white") +
  scale_fill_gradient(limits = c(0,0.05), low = "#800971", high = "#EDACE5", na.value = "#ffd2d9") +
  labs(title = "", x = "", y = "", fill = "P-Value") +
  theme_classic() +
  theme(axis.line = element_line(linewidth = .5, colour = "#242526")) +
  theme(axis.ticks = element_line(linewidth = .2, colour = "#242526")) +
  theme(plot.title = element_text(hjust = 0.5)) +
  theme(legend.position = "right") +
  theme(axis.text.x = element_text(size=25)) +
  theme(axis.text.y = element_text(size=25)) +
  scale_x_discrete(labels=c("T1","T2","T3","T4","T5","T6","T7","T8")) +
  scale_y_discrete(labels=c("T1","T2","T3","T4","T5","T6","T7","T8"))
heatmap_navct
```

```{r}
heatmap_dt <- ggplot(data_m_dt_targetonly, aes(x = t1, y = t2, fill = p.value.adj)) +
  geom_tile(aes(width = 1, height = 1), color = "white", lwd = 1) +
  geom_tile(data = subset(data_m_dt_targetonly, p.value.adj < 0.05), aes(width = 1, height = 1), 
            color = "white", lwd = 1) +
  geom_text(aes(label = ifelse(p.value.adj < 0.05, "*", ""), 
                fontface = ifelse(p.value.adj <0.05, "bold", "plain")),
            size = 10, vjust = 0.7, hjust = 0.5, color = "white") +
  scale_fill_gradient(limits = c(0,0.05), low = "#800971", high = "#EDACE5", na.value = "#ffd2d9") +
  labs(title = "", x = "", y = "", fill = "P-Value") +
  theme_classic() +
  theme(axis.line = element_line(linewidth = .5, colour = "#242526")) +
  theme(axis.ticks = element_line(linewidth = .2, colour = "#242526")) +
  theme(plot.title = element_text(hjust = 0.5)) +
  theme(legend.position = "right") +
  theme(axis.text.x = element_text(size=25)) +
  theme(axis.text.y = element_text(size=25)) +
  scale_x_discrete(labels=c("T1","T2","T3","T4","T5","T6","T7","T8")) +
  scale_y_discrete(labels=c("T1","T2","T3","T4","T5","T6","T7","T8"))
heatmap_dt
```

```{r}
heatmap_dwell <- ggplot(data_m_dwell_targetonly, aes(x = t1, y = t2, fill = p.value.adj)) +
  geom_tile(aes(width = 1, height = 1), color = "white", lwd = 1) +
  geom_tile(data = subset(data_m_dwell_targetonly, p.value.adj < 0.05), aes(width = 1, height = 1), 
            color = "white", lwd = 1) +
  geom_text(aes(label = ifelse(p.value.adj < 0.05, "*", ""), 
                fontface = ifelse(p.value.adj <0.05, "bold", "plain")),
            size = 10, vjust = 0.7, hjust = 0.5, color = "white") +
  scale_fill_gradient(limits = c(0,0.05), low = "#800971", high = "#EDACE5", na.value = "#ffd2d9") +
  labs(title = "", x = "", y = "", fill = "P-Value") +
  theme_classic() +
  theme(axis.line = element_line(linewidth = .5, colour = "#242526")) +
  theme(axis.ticks = element_line(linewidth = .2, colour = "#242526")) +
  theme(plot.title = element_text(hjust = 0.5)) +
  theme(legend.position = "right") +
  theme(axis.text.x = element_text(size=25)) +
  theme(axis.text.y = element_text(size=25)) +
  scale_x_discrete(labels=c("T1","T2","T3","T4","T5","T6","T7","T8")) +
  scale_y_discrete(labels=c("T1","T2","T3","T4","T5","T6","T7","T8"))
heatmap_dwell
```

```{r}
heatmap_teleport <- ggplot(data_m_teleport_targetonly, aes(x = t1, y = t2, fill = p.value.adj)) +
  geom_tile(aes(width = 1, height = 1), color = "white", lwd = 1) +
  geom_tile(data = subset(data_m_teleport_targetonly, p.value.adj < 0.05), aes(width = 1, height = 1), 
            color = "white", lwd = 1) +
  geom_text(aes(label = ifelse(p.value.adj < 0.05, "*", ""), 
                fontface = ifelse(p.value.adj <0.05, "bold", "plain")),
            size = 10, vjust = 0.7, hjust = 0.5, color = "white") +
  scale_fill_gradient(limits = c(0,0.05), low = "#800971", high = "#EDACE5", na.value = "#ffd2d9") +
  labs(title = "", x = "", y = "", fill = "P-Value") +
  theme_classic() +
  theme(axis.line = element_line(linewidth = .5, colour = "#242526")) +
  theme(axis.ticks = element_line(linewidth = .2, colour = "#242526")) +
  theme(plot.title = element_text(hjust = 0.5)) +
  theme(legend.position = "right") +
  theme(axis.text.x = element_text(size=25)) +
  theme(axis.text.y = element_text(size=25)) +
  scale_x_discrete(labels=c("T1","T2","T3","T4","T5","T6","T7","T8")) +
  scale_y_discrete(labels=c("T1","T2","T3","T4","T5","T6","T7","T8"))
heatmap_teleport
```


# Statistics with All Three Factors

```{r}
ya_target_data <- read.csv('/Users/yasminebassil/Documents/Emory/3_Research/Projects/NavAging_Paper/data/ya_merged_results.csv')
ya_target_data$Age <- "YA"
ya_target_data$Block_num <- as.factor(ya_target_data$Block_num)
oa_target_data <- read.csv('/Users/yasminebassil/Documents/Emory/3_Research/Projects/NavAging_Paper/data/oa_merged_results.csv')
oa_target_data$Age <- "OA"
oa_target_data$Block_num <- as.factor(oa_target_data$Block_num)
all_target_data <- rbind(ya_target_data, oa_target_data)
```

```{r}
# Initializing variables
outcome_measures <- c('Total_Time', 'Orientation_Time', 'Navigation_Time', 'Distance', 'Speed', 'Mean_Dwell', 'Teleportations')
outcome_names <- c('ct', 'orict','navct','dt','speed', 'dwell', 'teleport')
count <- 1

# Specify the directory where you want to save the CSV file
output_directory <- "/Users/yasminebassil/Documents/Emory/3_Research/Projects/NavAging_Paper/stat_tests/"

```

```{r}

# Looping through outcome measures
for (outcome in outcome_measures) {
  
  # Running the linear mixed model (LMM)
  lmm_formula <- as.formula(paste(outcome, "~ Block_num*Target_Name*Age + (1|Participant)"))
  lmm_outcome <- lmer(lmm_formula, data = all_target_data)
  assign(paste0("m_",outcome_names[count]), lmm_outcome)
  
  # Running the anova on the LMM
  anova_formula <- paste0("m_",outcome_names[count])
  anova <- anova(get(paste0("m_",outcome_names[count])))
  assign(paste0("m_",outcome_names[count], "_anova_tag1"), anova)
  
  # Figure 3
  
  ## Running emmeans on LMM for Age x Block
  emm_b <- emmeans(get(paste0("m_",outcome_names[count])), ~Age*Block_num)
  assign(paste0("emm_m_",outcome_names[count], "_b"), emm_b)

  ## Running contrasts on emmeans to get group differences
  emm_b_groups <- contrast(get(paste0("emm_m_",outcome_names[count], "_b")), method = "pairwise")
  emm_b_groups <- as.data.frame(emm_b_groups)
  assign(paste0("m_", outcome_names[count], "_b_groups_tag2"), emm_b_groups)
  
  ## Running contrasts on emmeans to get slope differences
  emm_b_slopes <- contrast(get(paste0("emm_m_",outcome_names[count], "_b")), interaction = "pairwise")
  emm_b_slopes <- data.frame(emm_b_slopes)
  assign(paste0("m_", outcome_names[count], "_b_slopes_tag3"), emm_b_slopes)
  
  # Figure 4
  
  ## Running emmeans on LMM for Age * Target
  emm_t <- emmeans(get(paste0("m_",outcome_names[count])), ~Age*Target_Name)
  assign(paste0("emm_m_",outcome_names[count], "_t"), emm_t)
  
  ## Running contrasts on emmeans to get group differences
  emm_t_groups <- contrast(get(paste0("emm_m_",outcome_names[count], "_t")), interaction = "pairwise")
  emm_t_groups <- data.frame(emm_t_groups)
  assign(paste0("m_", outcome_names[count], "_t_groups_tag4"), emm_t_groups)
  
  # Figure 5
  
  ## Running emmeans on LMM for Age * Block * Target
  emm_bt <- emmeans(get(paste0("m_",outcome_names[count])), ~Age*Block_num*Target_Name)
  assign(paste0("emm_m_",outcome_names[count], "_bt"), emm_bt)
  
  ## Running contrasts on emmeans to get group differences
  emm_bt_groups <- contrast(get(paste0("emm_m_",outcome_names[count], "_bt")), method = "pairwise")
  emm_bt_groups <- data.frame(emm_bt_groups)
  assign(paste0("emm_m_",outcome_names[count], "_bt_groups_tag5"), emm_bt_groups)
  
  ## Running emmeans on LMM for Age * Block | Target
  emm_bt_bytarget <- emmeans(get(paste0("m_",outcome_names[count])), ~Age*Block_num|Target_Name)
  assign(paste0("emm_m_",outcome_names[count], "_bt_bytarget"), emm_bt_bytarget)
  
  ## Running contrasts on emmeans to get slope differences sorted by target
  emm_bt_bytarget_slopes <- contrast(get(paste0("emm_m_",
                                                outcome_names[count],
                                                "_bt_bytarget")), 
                                     interaction = "pairwise")
  emm_bt_bytarget_slopes <- data.frame(emm_bt_bytarget_slopes)
  assign(paste0("emm_m_",outcome_names[count], "_bt_slopes_tag6"), emm_bt_bytarget_slopes)
  
  count <- count + 1
}
```

```{r}
tags <- c("tag1","tag2", "tag3", "tag4", "tag5", "tag6")
  
for (t in tags) {
  dataframes <- ls()
  
  # Filter dataframes that end with "tag1"
  dataframes_to_save <- dataframes[grep(t, dataframes)]
  
  # Create an empty list to store dataframes
  combined_dataframes <- list()
  
  # Loop through the selected dataframes, combine them, and add a "Source" column
  for (df_name in dataframes_to_save) {
    # Get the dataframe by name
    df <- get(df_name)
    
    # Add a "Source" column with the dataframe name
    df$Source <- df_name
    
    # Append the modified dataframe to the list
    combined_dataframes[[df_name]] <- df
  }
  
  # Combine all dataframes into one giant dataframe
  final_combined_dataframes <- do.call(rbind, combined_dataframes)
    
  # Define the CSV file name
  csv_file <- paste0(output_directory, paste0("stats_data_",
                                              t, ".csv"))
  # Save the combined dataframe as a CSV file
  write.csv(final_combined_dataframes, file = csv_file, row.names = TRUE)
  
  # Print a message to confirm the save
  cat("Saved combined data as", csv_file, "\n")
}
```

# PICKUP HERE


## Overall Model

```{r}
# Running linear mi
m_all_ct <- lmer(Total_Time ~ Block_num*Target_Name*Age + (1|Participant), data=all_target_data)
m_all_ct_anova_tag1 <- anova(m_all_ct)
m_all_ct_anova_tag1
# omnibus p-values - main effect of this variable
```

## Figure 3

```{r}
# Jasmine's code
m_ct_emm_b <- emmeans(m_all_ct,~Age*Block_num)

m_ct_b_groups <- contrast(m_ct_emm_b, method = "pairwise")
m_ct_b_groups_tag2 <- data.frame(m_ct_b_groups)
m_ct_b_groups_tag2
```

```{r}
# Difference between YA and OA in CHANGE in Blocks
m_ct_b_slopes <- contrast(m_ct_emm_b, interaction = "pairwise")
m_ct_b_slopes_tag3 <- data.frame(m_ct_b_slopes)
m_ct_b_slopes_tag3
```

## Figure 4

```{r}
# Jasmine's code
m_ct_emm_t <- emmeans(m_all_ct,~Age*Target_Name)

m_ct_t_groups <- contrast(m_ct_emm_t, method = "pairwise")
m_ct_t_groups_tag4 <- data.frame(m_ct_t_groups)
m_ct_t_groups_tag4
```

# Figure 5

```{r}
m_ct_bt <- emmeans(m_all_ct,~Age*Block_num*Target_Name)
m_ct_bt_groups_tag5 <- contrast(m_ct_bt, method = "pairwise")
m_ct_bt_groups_tag5 <- data.frame(m_ct_bt_groups_tag5)
m_ct_bt_groups_tag5
```

```{r}
m_ct_bt_bytarget <- emmeans(m_all_ct,~Age*Block_num|Target_Name)
m_ct_bt_slopes_tag6 <- contrast(m_ct_bt_bytarget, interaction = "pairwise")
m_ct_bt_slopes_tag6 <- data.frame(m_ct_bt_slopes_tag6)
m_ct_bt_slopes_tag6
```

```{r}

for (t in tags) {
  dataframes <- ls()
  
  # Filter dataframes that end with "tag1"
  dataframes_to_save <- dataframes[grep(t, dataframes)]

  # Create an empty list to store dataframes
  combined_dataframes <- list()

  # Loop through the selected dataframes, combine them, and add a "Source" column
  for (df_name in dataframes_to_save) {
    # Get the dataframe by name
    df <- get(df_name)
    
    # Add a "Source" column with the dataframe name
    df$Source <- df_name
    
    # Append the modified dataframe to the list
    combined_dataframes[[df_name]] <- df

    # Combine all dataframes into one giant dataframe
    final_combined_dataframes <- do.call(rbind, combined_dataframes)
    
    # Define the CSV file name
    csv_file <- paste0(output_directory, paste0("stats_data_",
                                                outcome_names[count], "_",
                                                t, ".csv"))
  
    # Save the combined dataframe as a CSV file
    write.csv(final_combined_dataframes, file = csv_file, row.names = TRUE)
    
    # Print a message to confirm the save
    cat("Saved combined data as", csv_file, "\n")
  }
  count <- count + 1
}
```

```{r}
sort_contrasts <- function(df) {
  # Check if the "contrast" column exists
  if (!("contrast" %in% names(df))) {
    stop("The dataframe does not have a 'contrast' column.")
  }
  
  # Create three separate dataframes based on the contrast values
  oa_ya <- df %>% filter(grepl("OA", contrast) & grepl("YA", contrast))
  two_oa <- df %>% filter(grepl("OA", contrast) & !grepl("YA", contrast))
  two_ya <- df %>% filter(grepl("YA", contrast) & !grepl("OA", contrast))
  
  return(list(both = oa_ya, oa = two_oa, ya = two_ya))
}
```

```{r}
contrasts <- sort_contrasts(m_ct_t_groups_tag4)
```

```{r}
contrasts_oa <- contrasts$oa
contrasts_oa$contrast <- gsub("OA", "", contrasts_oa$contrast)
contrasts_oa
```

```{r}
contrasts_ya <- contrasts$ya
contrasts_ya$contrast <- gsub("YA", "", contrasts_ya$contrast)
contrasts_ya
```

```{r}
contrasts_both <- contrasts$both
contrasts_both$contrast <- gsub("YA", "", contrasts_both$contrast)
contrasts_both$contrast <- gsub("OA", "", contrasts_both$contrast)
contrasts_both
```

```{r}
labels <- setNames(list(contrasts_ya, contrasts_oa, contrasts_both),
                  c("contrasts_ya", "contrasts_oa", "contrasts_both"))
count <- 0

for (i in labels) {
  count <- count + 1
  sep_data <- separate(i, contrast, into = c("t1", "t2"), sep = " - ")
  sep_data$t1 <- factor(filtered_data$t1, 
                                  levels = c("Automobile shop", "Police station ", 
                                             "Fire Station", "Bank", "Pawn Shop",
                                             "Pizzeria", "Quattroki Restaurant",
                                             "High School"))
  sep_data$t2 <- factor(filtered_data$t2, 
                                  levels = c("Automobile shop", "Police station ", 
                                             "Fire Station", "Bank", "Pawn Shop",
                                             "Pizzeria", "Quattroki Restaurant",
                                             "High School"))
  new <- data.frame()
  for (i in 1:nrow(sep_data)) {
    if (sep_data$t1[i] == "Automobile shop" | sep_data$t2[i] == "High School") {
      new <- rbind(new, sep_data[i, ])
    }
  }
  
  
  temp <- new$t1
  new$t1 <- new$t2
  new$t2 <- temp
  combined <- rbind(sep_data, new)
  
  combined <- combined[!(combined$t1 == "Police station " & combined$t2 == "Automobile shop"), ]
  combined <- combined[!(combined$t1 == "Fire Station" & combined$t2 == "Automobile shop"), ]
  combined <- combined[!(combined$t1 == "Bank" & combined$t2 == "Automobile shop"), ]
  combined <- combined[!(combined$t1 == "Pawn Shop" & combined$t2 == "Automobile shop"), ]
  combined <- combined[!(combined$t1 == "Pizzeria" & combined$t2 == "Automobile shop"), ]
  combined <- combined[!(combined$t1 == "Quattroki Restaurant" & combined$t2 == "Automobile shop"), ]
  combined <- combined[!(combined$t1 == "High School" & combined$t2 == "Automobile shop"), ]
  combined <- combined[!(combined$t1 == "High School" & combined$t2 == "Police station "), ]
  combined <- combined[!(combined$t1 == "High School" & combined$t2 == "Fire Station"), ]
  combined <- combined[!(combined$t1 == "High School" & combined$t2 == "Bank"), ]
  combined <- combined[!(combined$t1 == "High School" & combined$t2 == "Pawn Shop"), ]
  combined <- combined[!(combined$t1 == "High School" & combined$t2 == "Pizzeria"), ]
  combined <- combined[!(combined$t1 == "High School" & combined$t2 == "Quattroki Restaurant"), ]
  
  new_rows <- data.frame(t1 = c("Automobile shop", "Police station ", 
                                 "Fire Station", "Bank", "Pawn Shop", 
                                 "Pizzeria", "Quattroki Restaurant", 
                                 "High School"), 
                         t2 = c("Automobile shop", "Police station ",
                                "Fire Station", "Bank", 
                                "Pawn Shop", "Pizzeria",
                                "Quattroki Restaurant", "High School"),
                          estimate = c(rep(1, times = 8)),
                          SE = c(rep(1, times = 8)),
                          df = c(rep(1, times = 8)),
                          t.ratio = c(rep(1, times = 8)),
                          p.value = c(rep(1, times = 8)))
  new_combined <- rbind(combined, new_rows)
  
  # Assign filtered data to a new data frame with the label name
  assign(paste0("data_", names(labels)[count]), new_combined)
}

```




