---
title: "fig_8_stats"
output: html_document
date: "2024-11-07"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r global-options, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, warning=FALSE, message=FALSE)
```

```{r loading libraries, include=FALSE}

# This code chunk loads various libraries necessary to complete the data analysis and produce graphics
library(tidyverse)
library(stringr)
library(ez)
library(cowplot)
library(viridis)
library(viridisLite)
library("readxl")
library("ggcorrplot")
library(dplyr)
library(ltm)
library(plotrix)
library("viridis")
library("paletteer")
library(ggpubr)
library(rstatix)
library(lme4)
library(lmerTest)
library('emmeans')
```

```{r reading data, include=FALSE}
#This data chunk loads and tidies up the data

#This loads the data file as the variable "ya_data"
# ya_data <- read.csv('/Users/yasminebassil/Documents/Emory/3_Research/Projects/NavAging_Paper/data/ya_averaged_results.csv')

ya_data <- read.csv('/Users/emmafunderburg/Desktop/Research/BORICH LAB/8_navaging/NavAging_Paper/data/ya_averaged_results.csv')

# Tidying up the data
names(ya_data)[1] <- 'index'
names(ya_data)[2] <- 'Participant'
names(ya_data)[3] <- 'Block_num'
names(ya_data)[4] <- 'Total_Time'
names(ya_data)[5] <- 'Orientation_Time'
names(ya_data)[6] <- 'Navigation_Time'
names(ya_data)[7] <- 'Distance'
names(ya_data)[8] <- 'Speed'
names(ya_data)[9] <- 'Mean_Dwell'
names(ya_data)[10] <- 'Teleportations'
ya_data <- ya_data[ -c(1) ]
ya_data$Block_num <- as.factor(ya_data$Block_num)
sapply(ya_data, class)
ya_data$Age <- "YA"
ya_data

```

```{r reading data 2, include=FALSE}
#This data chunk loads and tidies up the data

#This loads the data file as the variable "ya_data"
# oa_data <- read.csv('/Users/yasminebassil/Documents/Emory/3_Research/Projects/NavAging_Paper/data/oa_averaged_results.csv')

oa_data <- read.csv('/Users/emmafunderburg/Desktop/Research/BORICH LAB/8_navaging/NavAging_Paper/data/oa_averaged_results.csv')

# Tidying up the data
names(oa_data)[1] <- 'index'
names(oa_data)[2] <- 'Participant'
names(oa_data)[3] <- 'Block_num'
names(oa_data)[4] <- 'Total_Time'
names(oa_data)[5] <- 'Orientation_Time'
names(oa_data)[6] <- 'Navigation_Time'
names(oa_data)[7] <- 'Distance'
names(oa_data)[8] <- 'Speed'
names(oa_data)[9] <- 'Mean_Dwell'
names(oa_data)[10] <- 'Teleportations'
oa_data <- oa_data[ -c(1) ]
oa_data$Block_num <- as.factor(oa_data$Block_num)
sapply(oa_data, class)
oa_data$Age <- "OA"
oa_data




```

```{r}

# load non nav data

#non_nav_data <- read.csv('/Users/emmafunderburg/Desktop/Research/BORICH LAB/8_navaging/NavAging_Paper/data/non_nav_data.csv')

# data frame of YAs already created - ya_data

# create data frame of OA high

oa_data_high <- oa_data[-c(4,5,6,16,17,18,19,20,21,34,35,36,40,41,42,49,50,51,52,53,54,58,59,60,61,62,63,64,65,66),]

# add OA high label as nara_group

oa_data_high$nara_group <- factor(c('OA High'))

# create data frame of OA low 

oa_data_low <- oa_data[c(4,5,6,16,17,18,19,20,21,34,35,36,40,41,42,49,50,51,52,53,54,58,59,60,61,62,63,64,65,66),]

# add OA low label as nara_group

oa_data_low$nara_group <- factor(c('OA Low'))

# add YA label as nara_group

ya_data$nara_group <- factor(c('YA'))

# bind oa_data_low, oa_data_high, and ya_data

all_data <- rbind(ya_data, oa_data_low, oa_data_high)

# alphabetize by participant

all_data <- all_data[order(all_data$Participant),]


```


# LMM & ANOVA 
```{r}


# This runs ANOVA tests for all outcome measures
outcome_measures <- c('Total_Time', 'Orientation_Time', 'Navigation_Time', 'Distance', 'Speed', 'Mean_Dwell', 'Teleportations')
outcome_names <- c('ct', 'orict','navct','dt','speed', 'dwell', 'teleport')
count <- 1

# Looping through outcome measures
#for (outcome in outcome_measures) {
  
  # Running the linear mixed model (LMM)
  lmm_formula <- as.formula(paste(outcome, "~ Block_num*nara_group + (1|Participant)"))
  lmm_outcome <- lmer(lmm_formula, data = all_data)
  assign(paste0("m_",outcome_names[count]), lmm_outcome)
  
  # Running the anova on the LMM
  anova_formula <- paste0("m_",outcome_names[count])
  anova <- anova(get(paste0("m_",outcome_names[count])))
  assign(paste0("m_",outcome_names[count], "_anova"), anova)
  
  # Printing all anova outputs
  cat("\nANOVA for", outcome, ":\n")
  print(anova)
  
  # Running contrasts on LMM for BLOCK
  contrast_b <- emmeans(get(paste0("m_",outcome_names[count])), ~Block_num)
  assign(paste0("emm_m_",outcome_names[count], "_b"), contrast_b)
  
  # Running pairs on contrast
  emm_pairs_b <- pairs(get(paste0("emm_m_",outcome_names[count], "_b")))
  emm_pairs_b <- as.data.frame(emm_pairs_b)
  assign(paste0("m_", outcome_names[count], "_block"), emm_pairs_b)
  
  # Running contrasts on LMM for TARGET
  contrast_t <- emmeans(get(paste0("m_",outcome_names[count])), ~Target_Name)
  assign(paste0("emm_m_",outcome_names[count], "_t"), contrast_t)
  
  # Running pairs on contrast
  emm_pairs_t <- pairs(get(paste0("emm_m_",outcome_names[count], "_t")))
  emm_pairs_t <- as.data.frame(emm_pairs_t)
  assign(paste0("m_", outcome_names[count], "_targetonly"), emm_pairs_t)
  
  # Running contrasts on LMM for BLOCK:TARGET interaction
  contrast_bt <- emmeans(get(paste0("m_",outcome_names[count])), ~Block_num|Target_Name)
  assign(paste0("emm_m_",outcome_names[count]), contrast_bt)
  
  # Running pairs on contrast
  emm_pairs_bt <- pairs(get(paste0("emm_m_",outcome_names[count])))
  emm_pairs_bt <- as.data.frame(emm_pairs_bt)
  assign(paste0("m_", outcome_names[count], "_blocktarget"), emm_pairs_bt)
  
  # Updating count variable to loop through outcome names
  count <- count + 1
}

```


# Dwell Time LMM
```{r}

m_dwell <- lmer(Mean_Dwell ~ Block_num*nara_group + (1|Participant), data=all_data)
m_dwell_anova <- anova(m_dwell)
m_dwell_anova

# p = 0.002327 **

```

# Total Time LMM
```{r}

m_totaltime <- lmer(Total_Time ~ Block_num*nara_group + (1|Participant), data=all_data)
m_totaltime_anova <- anova(m_totaltime)
m_totaltime_anova

# p = 0.01427 **

```

# Orientation Time LMM
```{r}

m_ortime <- lmer(Orientation_Time ~ Block_num*nara_group + (1|Participant), data=all_data)
m_ortime_anova <- anova(m_ortime)
m_ortime_anova

# p = 2.747e-06 ***

```

# Navigation Time LMM
```{r}

m_navtime <- lmer(Navigation_Time ~ Block_num*nara_group + (1|Participant), data=all_data)
m_navtime_anova <- anova(m_navtime)
m_navtime_anova

# p = 0.02747 *

```

# Distance LMM
```{r}

m_distance <- lmer(Distance ~ Block_num*nara_group + (1|Participant), data=all_data)
m_distance_anova <- anova(m_distance)
m_distance_anova

# p = 0.6248

```

# Speed LMM
```{r}

m_speed <- lmer(Speed ~ Block_num*nara_group + (1|Participant), data=all_data)
m_speed_anova <- anova(m_speed)
m_speed_anova

# p = 9.318e-06***

```

# Teleportations LMM
```{r}

m_tele <- lmer(Teleportations ~ Block_num*nara_group + (1|Participant), data=all_data)
m_tele_anova <- anova(m_tele)
m_tele_anova

# p = 0.6163

```

# Code Below Updated from Figure 4

```{r}
# This runs ANOVA tests for all outcome measures
outcome_measures <- c('Total_Time', 'Orientation_Time', 'Navigation_Time', 'Distance', 'Speed', 'Mean_Dwell', 'Teleportations')
outcome_names <- c('ct', 'orict','navct','dt','speed', 'dwell', 'teleport')
count <- 1

# Looping through outcome measures
for (outcome in outcome_measures) {
  
  # Running the linear mixed model (LMM)
  lmm_formula <- as.formula(paste(outcome, "~ Block_num*nara_group + (1|Participant)"))
  lmm_outcome <- lmer(lmm_formula, data = all_data)
  assign(paste0("m_",outcome_names[count]), lmm_outcome)
  
  # Running the anova on the LMM
  anova_formula <- paste0("m_",outcome_names[count])
  anova <- anova(get(paste0("m_",outcome_names[count])))
  assign(paste0("m_",outcome_names[count], "_anova"), anova)
  
  # Printing all anova outputs
  cat("\nANOVA for", outcome, ":\n")
  print(anova)
  
  # Running contrasts on LMM for BLOCK
  contrast_b <- emmeans(get(paste0("m_",outcome_names[count])), ~Block_num)
  assign(paste0("emm_m_",outcome_names[count], "_b"), contrast_b)
  
  # Running pairs on contrast
  emm_pairs_b <- pairs(get(paste0("emm_m_",outcome_names[count], "_b")))
  emm_pairs_b <- as.data.frame(emm_pairs_b)
  assign(paste0("m_", outcome_names[count], "_block"), emm_pairs_b)
  
  # Running contrasts on LMM for NARA Group
  contrast_t <- emmeans(get(paste0("m_",outcome_names[count])), ~nara_group)
  assign(paste0("emm_m_",outcome_names[count], "_t"), contrast_t)
  
  # Running pairs on contrast
  emm_pairs_t <- pairs(get(paste0("emm_m_",outcome_names[count], "_t")))
  emm_pairs_t <- as.data.frame(emm_pairs_t)
  assign(paste0("m_", outcome_names[count], "_targetonly"), emm_pairs_t)
  
  # Running contrasts on LMM for BLOCK:NARA Group interaction
  contrast_bt <- emmeans(get(paste0("m_",outcome_names[count])), ~Block_num|nara_group)
  assign(paste0("emm_m_",outcome_names[count]), contrast_bt)
  
  # Running pairs on contrast
  emm_pairs_bt <- pairs(get(paste0("emm_m_",outcome_names[count])))
  emm_pairs_bt <- as.data.frame(emm_pairs_bt)
  assign(paste0("m_", outcome_names[count], "_blocknara"), emm_pairs_bt)
  
  # Updating count variable to loop through outcome names
  count <- count + 1
}
```


```{r}
rm("anova")

# List all dataframes in the global environment
dataframes <- ls()

# Filter dataframes that end with "anova"
dataframes_to_save_anova <- dataframes[grep("anova$", dataframes)]

# Create an empty list to store dataframes
combined_dataframes_anova <- list()

# Loop through the selected dataframes, combine them, and add a "Source" column
for (df_name in dataframes_to_save_anova) {
  # Get the dataframe by name
  df <- get(df_name)
  
  # Add a "Source" column with the dataframe name
  df$Source <- df_name
  
  # Append the modified dataframe to the list
  combined_dataframes_anova[[df_name]] <- df
}

# Combine all dataframes into one giant dataframe
final_combined_dataframe_anova <- do.call(rbind, combined_dataframes_anova)

# Specify the directory where you want to save the CSV file
#output_directory <- "/Users/yasminebassil/Documents/Emory/3_Research/Projects/NavAging_Paper/stat_tests/"
output_directory <- "/Users/emmafunderburg/Desktop/Research/BORICH LAB/8_navaging/NavAging_Paper/stat_tests/"


# Define the CSV file name
csv_file <- paste0(output_directory, "fig8_anova_data.csv")

# Save the combined dataframe as a CSV file
write.csv(final_combined_dataframe_anova, file = csv_file, row.names = TRUE)

# Print a message to confirm the save
cat("Saved combined data as", csv_file, "\n")

```


```{r}

# List all dataframes in the global environment
dataframes <- ls()

# Filter dataframes that end with "anova"
dataframes_to_save_block <- dataframes[grep("block$", dataframes)]

# Create an empty list to store dataframes
combined_dataframes_block <- list()

# Loop through the selected dataframes, combine them, and add a "Source" column
for (df_name in dataframes_to_save_block) {
  # Get the dataframe by name
  df <- get(df_name)
  
  # Add a "Source" column with the dataframe name
  df$Source <- df_name
  
  # Append the modified dataframe to the list
  combined_dataframes_block[[df_name]] <- df
}

# Combine all dataframes into one giant dataframe
final_combined_dataframe_block <- do.call(rbind, combined_dataframes_block)

# Specify the directory where you want to save the CSV file
#output_directory <- "/Users/yasminebassil/Documents/Emory/3_Research/Projects/NavAging_Paper/stat_tests/"
output_directory <- "/Users/emmafunderburg/Desktop/Research/BORICH LAB/8_navaging/NavAging_Paper/stat_tests/"

# Define the CSV file name
csv_file <- paste0(output_directory, "fig8_all_block_data.csv")

# Save the combined dataframe as a CSV file
write.csv(final_combined_dataframe_block, file = csv_file, row.names = TRUE)

# Print a message to confirm the save
cat("Saved combined data as", csv_file, "\n")

```



```{r}

# List all dataframes in the global environment
dataframes2 <- ls()

# Filter dataframes that end with "anova"
dataframes_to_save_blocknara <- dataframes2[grep("blocktarget$", dataframes2)]

# Create an empty list to store dataframes
combined_dataframes_blocknara <- list()

# Loop through the selected dataframes, combine them, and add a "Source" column
for (df_name in combined_dataframes_blocknara) {
  # Get the dataframe by name
  df <- get(df_name)
  
  # Add a "Source" column with the dataframe name
  df$Source <- df_name
  
  # Append the modified dataframe to the list
  combined_dataframes_blocknara[[df_name]] <- df
}

# Combine all dataframes into one giant dataframe
final_combined_dataframe_blocknara <- do.call(rbind, combined_dataframes_blocknara)

# Specify the directory where you want to save the CSV file
#output_directory <- "/Users/yasminebassil/Documents/Emory/3_Research/Projects/NavAging_Paper/stat_tests/"
output_directory <- "/Users/emmafunderburg/Desktop/Research/BORICH LAB/8_navaging/NavAging_Paper/stat_tests/"


# Define the CSV file name
csv_file <- paste0(output_directory, "all_blocknara_data.csv")

# Save the combined dataframe as a CSV file
write.csv(final_combined_dataframe_blocknara, file = csv_file, row.names = TRUE)

# Print a message to confirm the save
cat("Saved combined data as", csv_file, "\n")
```


```{r}

# List all dataframes in the global environment
dataframes3 <- ls()

# Filter dataframes that end with "anova"
dataframes_to_save_targetonly <- dataframes3[grep("targetonly$", dataframes3)]

# Create an empty list to store dataframes
combined_dataframes_targetonly <- list()

# Loop through the selected dataframes, combine them, and add a "Source" column
for (df_name in dataframes_to_save_targetonly) {
  # Get the dataframe by name
  df <- get(df_name)
  
  # Add a "Source" column with the dataframe name
  df$Source <- df_name
  
  # Append the modified dataframe to the list
  combined_dataframes_targetonly[[df_name]] <- df
}

# Combine all dataframes into one giant dataframe
final_combined_dataframe_targetonly <- do.call(rbind, combined_dataframes_targetonly)

# Specify the directory where you want to save the CSV file
#output_directory <- "/Users/yasminebassil/Documents/Emory/3_Research/Projects/NavAging_Paper/stat_tests/"
output_directory <- "/Users/emmafunderburg/Desktop/Research/BORICH LAB/8_navaging/NavAging_Paper/stat_tests/"

# Define the CSV file name
csv_file <- paste0(output_directory, "all_nara_data.csv")

# Save the combined dataframe as a CSV file
write.csv(final_combined_dataframe_targetonly, file = csv_file, row.names = TRUE)

# Print a message to confirm the save
cat("Saved combined data as", csv_file, "\n")
```



