
```{r global-options, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, warning=FALSE, message=FALSE)
```

```{r loading libraries, include=FALSE}
# This code chunk loads various libraries necessary to complete the data analysis and produce graphics
library(tidyverse)
library(stringr)
library(ez)
library(cowplot)
library("readxl")
library("ggcorrplot")
library(dplyr)
library(ltm)
library(plotrix)
library("viridis")
library("paletteer")
library(ggpubr)
library(rstatix)
library(lme4)
#install.packages("lmerTest")
library(lmerTest)
#install.packages('emmeans')
library('emmeans')
#install.packages("svglite")
library(svglite)
library(tidyquant)
library(ggdist)
library(ggthemes)
library(gghalves)
```

```{r}
ya_data <- read.csv('/Volumes/YB_Drive/NavAging_Paper/data/ya_averaged_results.csv')
ya_nav_data <- read.csv('/Volumes/YB_Drive/NavAging_Paper/data/ya_merged_results.csv')
oa_data <- read.csv('/Volumes/YB_Drive/NavAging_Paper/data/oa_averaged_results.csv')
oa_nav_data <- read.csv('/Volumes/YB_Drive/NavAging_Paper/data/oa_merged_results.csv')
non_nav_data <- read.csv('/Volumes/YB_Drive/NavAging_Paper/data/non_nav_data.csv')

# CHANGE THE END DEPENDING ON YOUR FIG NUMBER
path_to_figs <- "/Volumes/YB_Drive/NavAging_Paper/figure_creation/plots/fig6"
```

```{r reading data, include=FALSE}
# Tidying up the data
ya_data<- ya_data %>% mutate(Age = 'YA')
ya_data
names(ya_data)[1] <- 'index'
names(ya_data)[2] <- 'Participant'
names(ya_data)[3] <- 'Block_num'
names(ya_data)[4] <- 'Total_Time'
names(ya_data)[5] <- 'Orientation_Time'
names(ya_data)[6] <- 'Navigation_Time'
names(ya_data)[7] <- 'Distance'
names(ya_data)[8] <- 'Speed'
names(ya_data)[9] <- 'Mean_Dwell'
names(ya_data)[10] <- 'Teleportations'
names(ya_data)[11] <- 'Age'
ya_data <- ya_data[ -c(1) ]
ya_data$Block_num <- as.factor(ya_data$Block_num)
sapply(ya_data, class)
ya_data

# Tidying up the data
oa_data<- oa_data %>% mutate(Age = 'OA')
oa_data
names(oa_data)[1] <- 'index'
names(oa_data)[2] <- 'Participant'
names(oa_data)[3] <- 'Block_num'
names(oa_data)[4] <- 'Total_Time'
names(oa_data)[5] <- 'Orientation_Time'
names(oa_data)[6] <- 'Navigation_Time'
names(oa_data)[7] <- 'Distance'
names(oa_data)[8] <- 'Speed'
names(oa_data)[9] <- 'Mean_Dwell'
names(oa_data)[10] <- 'Teleportations'
names(oa_data)[11] <- 'Age'
oa_data <- oa_data[ -c(1) ]
oa_data$Block_num <- as.factor(oa_data$Block_num)
sapply(oa_data, class)
oa_data

data <- rbind(ya_data, oa_data)
```

```{r reading more data, include=FALSE}

# Tidying up the data
ya_nav_data<- ya_nav_data %>% mutate(Age = 'YA')
names(ya_nav_data)[1] <- 'index'
names(ya_nav_data)[2] <- 'Participant'
names(ya_nav_data)[3] <- 'Block_num'
names(ya_nav_data)[4] <- 'Target_Name'
names(ya_nav_data)[5] <- 'Total_Time'
names(ya_nav_data)[6] <- 'Orientation_Time'
names(ya_nav_data)[7] <- 'Navigation_Time'
names(ya_nav_data)[8] <- 'Distance'
names(ya_nav_data)[9] <- 'Speed'
names(ya_nav_data)[10] <- 'Mean_Dwell'
names(ya_nav_data)[11] <- 'Teleportations'
names(ya_nav_data)[12] <- 'Age'
ya_nav_data <- ya_nav_data[ -c(1) ]
ya_nav_data$Block_num <- as.factor(ya_nav_data$Block_num)
sapply(ya_nav_data, class)

desired_order <- c("Automobile shop", "Police station ", "Fire Station", "Bank", "Pawn Shop", "Pizzeria", "Quattroki Restaurant", "High School")
# Reorder the levels of Target_Name
ya_nav_data$Target_Name <- factor(ya_nav_data$Target_Name, levels = desired_order)

# Tidying up the data
oa_nav_data<- oa_nav_data %>% mutate(Age = 'OA')
names(oa_nav_data)[1] <- 'index'
names(oa_nav_data)[2] <- 'Participant'
names(oa_nav_data)[3] <- 'Block_num'
names(oa_nav_data)[4] <- 'Target_Name'
names(oa_nav_data)[5] <- 'Total_Time'
names(oa_nav_data)[6] <- 'Orientation_Time'
names(oa_nav_data)[7] <- 'Navigation_Time'
names(oa_nav_data)[8] <- 'Distance'
names(oa_nav_data)[9] <- 'Speed'
names(oa_nav_data)[10] <- 'Mean_Dwell'
names(oa_nav_data)[11] <- 'Teleportations'
names(oa_nav_data)[12] <- 'Age'
oa_nav_data <- oa_nav_data[ -c(1) ]
oa_nav_data$Block_num <- as.factor(oa_nav_data$Block_num)
sapply(oa_nav_data, class)

desired_order <- c("Automobile shop", "Police station ", "Fire Station", "Bank", "Pawn Shop", "Pizzeria", "Quattroki Restaurant", "High School")
# Reorder the levels of Target_Name
oa_nav_data$Target_Name <- factor(oa_nav_data$Target_Name, levels = desired_order)

nav_data <- rbind(ya_nav_data, oa_nav_data)
```

```{r organizing data, include=FALSE}
b1 <- subset(nav_data, Block_num == 1)
rownames(b1) <- NULL
b2 <- subset(nav_data, Block_num == 2)
rownames(b2) <- NULL 
b3 <- subset(nav_data, Block_num == 3)
rownames(b3) <- NULL 

mean_data <- subset(b3, select = c(Participant, Age))

for (i in 1:nrow(b3)) {
  mean_data$Total_Time[i] <- (b3$Total_Time[i] + b2$Total_Time[i]+b1$Total_Time[i])/3
  mean_data$Orientation_Time[i] <- (b3$Orientation_Time[i] + b2$Orientation_Time[i]+b1$Orientation_Time[i])/3
  mean_data$Navigation_Time[i] <- (b3$Navigation_Time[i] + b2$Navigation_Time[i]+b1$Navigation_Time[i])/3
  mean_data$Distance[i] <- (b3$Distance[i] + b2$Distance[i]+b1$Distance[i])/3
  mean_data$Speed[i] <- (b3$Speed[i] + b2$Speed[i]+b1$Speed[i])/3
  mean_data$Mean_Dwell[i] <- (b3$Mean_Dwell[i] + b2$Mean_Dwell[i]+b1$Mean_Dwell[i])/3
  mean_data$Var_X[i] <- (b3$Var_X[i] + b2$Var_X[i]+b1$Var_X[i])/3
  mean_data$Var_Y[i] <- (b3$Var_Y[i] + b2$Var_Y[i]+b1$Var_Y[i])/3
  mean_data$Var_Z[i] <- (b3$Var_Z[i] + b2$Var_Z[i]+b1$Var_Z[i])/3
  mean_data$Teleportations[i] <- (b3$Teleportations[i] + b2$Teleportations[i]+b1$Teleportations[i])/3
}

mean_data$Age <- factor(mean_data$Age, levels=c("YA", "OA"))
```



```{r}
data_plot <- ggplot(non_nav_data, aes(x=group, y=nara, color = group))+
  geom_point(size=2, position=position_jitter(h=0,w=0.15),show.legend = TRUE) +
  scale_color_manual(values =c('#5E7AFA','#FF9FAF'))+
  scale_x_discrete(limits = c("YA", "OA"))+
  stat_summary(fun.args = list(mean_se), geom="crossbar",  width=.3, size = .5,  color="#242526") +
  stat_summary( fun = "mean",fun.args = list(mult=1), geom="point", size = 1.5, color="black") +
  labs(color= "Participant", y="NARA Score (%)", x="Age Group")+
  theme_classic()+
  theme(panel.background = element_rect(fill = "white", linewidth = .5, colour = "#242526"))+
  #theme(axis.line = element_line(linewidth = .5, colour = "#242526"))+
  theme(axis.ticks = element_line(linewidth = .2, colour = "#242526"))+
  theme(plot.title = element_text(hjust = 0.5))+
  theme(legend.position = 'none')
data_plot

ggsave(file=paste0(path_to_figs, "_nara_bar.svg"), height = 5, width = 5, plot=data_plot)
```

```{r}
rain_nara <-ggplot(non_nav_data, aes(x = factor(group), y=nara, fill=group)) +
  scale_fill_manual(values =c('#5E7AFA','#FF9FAF'))+
  scale_y_continuous(breaks = scales::pretty_breaks(n= 4))+
  labs(color= "Participant", y="NARA Score (%)", x = ' ')+
  scale_x_discrete(limits = c("YA", "OA"))+
  theme_classic()+
  theme(axis.line = element_line(linewidth = .5, colour = "#242526"))+
  theme(axis.ticks = element_line(linewidth = .2, colour = "#242526"))+
  theme(plot.title = element_text(hjust = 0.5))+
  theme(legend.position = "none")+
  theme(axis.text.x = element_text(size=20))+
  theme(axis.text.y = element_text(size=20))+
  theme(axis.title.y = element_text(size=20))+
  stat_halfeye(
    # adjust bandwidth
    adjust = 0.5,
    # move to the right
    justification = -0.2,
    # remove the slub interval
    .width = 0,
    point_colour = NA,
    scale = 0.5 ##  <(**new parameter**)
  ) +
  geom_boxplot(
    width = 0.12,
    # removing outliers
    outlier.color = NA,
    alpha = 0.5
  )+
  geom_half_point(
    aes(color = group),
    side = 'l',
    range_scale = .4,
    alpha = .3,
    position = position_jitter(seed = 1, width = .12, height = 0)
  ) +scale_color_manual(values =c('#5E7AFA','#FF9FAF'))
rain_nara

ggsave(file=paste0(path_to_figs, "_nara_rain.svg"), plot=data_plot)
```

```{r}
corr_nara <-ggplot(non_nav_data, aes(x=age, y=nara, color = group))+
  geom_point(size=2)+
  #labs(color = c('#FF9FAF','#5E7AFA'))+
  scale_color_manual(values =c('#5E7AFA','#FF9FAF'))+
  labs(y="NARA Score (%)", x = 'Age')+
  theme_classic()+
  theme(axis.line = element_line(linewidth = .5, colour = "#242526"))+
  theme(axis.ticks = element_line(linewidth = .2, colour = "#242526"))+
  theme(plot.title = element_text(hjust = 0.5))+
  theme(legend.position = "none")+
  theme(axis.text.x = element_text(size=20))+
  theme(axis.text.y = element_text(size=20))+
  theme(axis.title.y = element_text(size=20))+
  theme(axis.title.x = element_text(size=20))+
  geom_smooth(aes(age,nara, group=group), method="lm", se=TRUE, color = "#242526", fill = 'lightgray')
 
corr_nara


ggsave(file=paste0(path_to_figs, "_nara_corr.svg"), height = 5, width = 5, plot=data_plot)
```

```{r}
corr_nara_stats <- cor.test(x=non_nav_data$age, y=non_nav_data$nara, method = 'spearman')

corr_nara_stats

non_nav_ya_data <- non_nav_data %>% filter(group == 'YA')

##Filter by group in non_nav_data_final
corr_nara_stats_ya <- cor.test(x=non_nav_ya_data$age, y=non_nav_ya_data$nara, method = 'spearman')

corr_nara_stats_ya

non_nav_oa_data <- non_nav_data %>% filter(group == 'OA')

corr_nara_stats_oa <- cor.test(x=non_nav_oa_data$age, y=non_nav_oa_data$nara, method = 'spearman')

corr_nara_stats_oa
```
```{r}
# Labeling non_nav_data dataframe

# Create nara_labels column based on participant type and NARA scores
non_nav_data$nara_labels <- ifelse(non_nav_data$group == "OA" & non_nav_data$nara > 50, "oa_high",
                             ifelse(non_nav_data$group == "OA" & non_nav_data$nara < 50, "oa_low",
                             ifelse(non_nav_data$group == "YA", "YA", NA)))
```


```{r}

corr_nara_three <-ggplot(non_nav_data, aes(x=age, y=nara, color = nara_labels))+
  geom_point(size=2)+
  #labs(color = c('#FF9FAF','#5E7AFA'))+
  scale_color_manual(values =c('#7f00fe','#c5b3de','#FF9FAF'))+
  labs(y="NARA Score (%)", x = 'Age')+
  theme_classic()+
  theme(axis.line = element_line(linewidth = .5, colour = "#242526"))+
  theme(axis.ticks = element_line(linewidth = .2, colour = "#242526"))+
  theme(plot.title = element_text(hjust = 0.5))+
  theme(legend.position = "none")+
  theme(axis.text.x = element_text(size=20))+
  theme(axis.text.y = element_text(size=20))+
  theme(axis.title.y = element_text(size=20))+
  theme(axis.title.x = element_text(size=20))+
  geom_smooth(aes(age,nara, group=nara_labels), method="lm", se=TRUE, color = "#242526", fill = 'lightgray')
 
corr_nara_three

ggsave(file=paste0(path_to_figs, "_nara_three.svg"), height = 5, width = 5, plot=corr_nara_three)
```

```{r}
non_nav_oa_high_data <- non_nav_data %>% filter(nara_labels == 'oa_high')

corr_nara_three_stats_oa_high <- cor.test(x=non_nav_oa_high_data$age, y=non_nav_oa_high_data$nara, method = 'spearman')

corr_nara_three_stats_oa_high

non_nav_oa_low_data <- non_nav_data %>% filter(nara_labels == 'oa_low')

corr_nara_three_stats_oa_low <- cor.test(x=non_nav_oa_low_data$age, y=non_nav_oa_low_data$nara, method = 'spearman')

corr_nara_three_stats_oa_low
```